In [1]:
import pandas as pd
subway = pd.read_csv('서울 지하철역 좌표.csv')
subway_list = list((set(subway['역명'])))
subway_list.sort()

In [2]:
len(subway_list)

244

In [32]:
#-*- coding: utf-8 -*-
import os
import sys
import urllib.request
import json

url = "https://openapi.naver.com/v1/datalab/search"

for i in range(len(subway_list)):
    client_id = "W5USlEAS7_mhRRbY_4A_"
    client_secret = "duCoBBdkM6"

    request = urllib.request.Request(url)

    request.add_header("X-Naver-Client-Id",client_id)
    request.add_header("X-Naver-Client-Secret",client_secret)
    request.add_header("Content-Type","application/json")
    response = urllib.request.urlopen(request, data=body.encode("utf-8"))
    rescode = response.getcode()
    
#     url = "https://openapi.naver.com/v1/datalab/search"
    body = {"startDate":"2020-01-24",
            "endDate":"2020-08-31",
            "timeUnit":"date",
            "keywordGroups":[
                {
                    "groupName":"{}역".format(subway_list[i]),
                    "keywords":["맛집","카페","놀거리","볼거리","데이트","나들이","구경","약속","모임","장소"]
                }
            ]
           }

    if(rescode==200):
        response_body = response.read()
        print(response_body.decode('utf-8'))
    else:
        print("Error Code:" + rescode)

    data = json.loads(response_body)

    tmp = pd.DataFrame(data['results'])
    print(tmp)

res = data['results'][0]['data']
pd.DataFrame(res)

{"startDate":"2020-01-24","endDate":"2020-08-31","timeUnit":"date","results":[{"title":"명동역","keywords":["맛집","카페","놀거리","볼거리","데이트","나들이","구경","약속","모임","장소"],"data":[{"period":"2020-01-24","ratio":44.39466},{"period":"2020-01-25","ratio":45.98764},{"period":"2020-01-26","ratio":59.38209},{"period":"2020-01-27","ratio":47.804},{"period":"2020-01-28","ratio":32.34906},{"period":"2020-01-29","ratio":32.42352},{"period":"2020-01-30","ratio":33.19132},{"period":"2020-01-31","ratio":33.33902},{"period":"2020-02-01","ratio":47.72832},{"period":"2020-02-02","ratio":45.66783},{"period":"2020-02-03","ratio":31.69112},{"period":"2020-02-04","ratio":32.29047},{"period":"2020-02-05","ratio":32.15497},{"period":"2020-02-06","ratio":32.75554},{"period":"2020-02-07","ratio":35.11877},{"period":"2020-02-08","ratio":50.62376},{"period":"2020-02-09","ratio":52.89909},{"period":"2020-02-10","ratio":36.70076},{"period":"2020-02-11","ratio":37.08893},{"period":"2020-02-12","ratio":36.56526},{"period":"2020-02-13","ratio":36.9864},{"period":"2020-02-14","ratio":41.91059},{"period":"2020-02-15","ratio":57.95146},{"period":"2020-02-16","ratio":53.50577},{"period":"2020-02-17","ratio":36.37606},{"period":"2020-02-18","ratio":37.20856},{"period":"2020-02-19","ratio":36.56038},{"period":"2020-02-20","ratio":35.31896},{"period":"2020-02-21","ratio":33.88955},{"period":"2020-02-22","ratio":44.03823},{"period":"2020-02-23","ratio":42.10712},{"period":"2020-02-24","ratio":28.92629},{"period":"2020-02-25","ratio":29.42433},{"period":"2020-02-26","ratio":28.52469},{"period":"2020-02-27","ratio":28.97878},{"period":"2020-02-28","ratio":29.03249},{"period":"2020-02-29","ratio":38.97365},{"period":"2020-03-01","ratio":38.21928},{"period":"2020-03-02","ratio":29.74658},{"period":"2020-03-03","ratio":30.50218},{"period":"2020-03-04","ratio":31.08322},{"period":"2020-03-05","ratio":32.10004},{"period":"2020-03-06","ratio":33.37687},{"period":"2020-03-07","ratio":44.24696},{"period":"2020-03-08","ratio":52.00556},{"period":"2020-03-09","ratio":32.53704},{"period":"2020-03-10","ratio":31.97675},{"period":"2020-03-11","ratio":35.18102},{"period":"2020-03-12","ratio":34.62928},{"period":"2020-03-13","ratio":36.7679},{"period":"2020-03-14","ratio":54.42372},{"period":"2020-03-15","ratio":54.26503},{"period":"2020-03-16","ratio":35.61314},{"period":"2020-03-17","ratio":35.46422},{"period":"2020-03-18","ratio":38.12284},{"period":"2020-03-19","ratio":34.88074},{"period":"2020-03-20","ratio":39.38258},{"period":"2020-03-21","ratio":57.36188},{"period":"2020-03-22","ratio":61.94795},{"period":"2020-03-23","ratio":38.81497},{"period":"2020-03-24","ratio":38.13871},{"period":"2020-03-25","ratio":38.20951},{"period":"2020-03-26","ratio":35.1859},{"period":"2020-03-27","ratio":38.49393},{"period":"2020-03-28","ratio":55.50401},{"period":"2020-03-29","ratio":58.00761},{"period":"2020-03-30","ratio":37.06574},{"period":"2020-03-31","ratio":37.33185},{"period":"2020-04-01","ratio":36.61897},{"period":"2020-04-02","ratio":37.3111},{"period":"2020-04-03","ratio":39.9624},{"period":"2020-04-04","ratio":58.2725},{"period":"2020-04-05","ratio":59.05007},{"period":"2020-04-06","ratio":36.56771},{"period":"2020-04-07","ratio":36.63973},{"period":"2020-04-08","ratio":36.76423},{"period":"2020-04-09","ratio":36.76545},{"period":"2020-04-10","ratio":39.20924},{"period":"2020-04-11","ratio":57.27033},{"period":"2020-04-12","ratio":59.98266},{"period":"2020-04-13","ratio":38.58792},{"period":"2020-04-14","ratio":41.40645},{"period":"2020-04-15","ratio":60.02905},{"period":"2020-04-16","ratio":38.44388},{"period":"2020-04-17","ratio":39.52051},{"period":"2020-04-18","ratio":63.85708},{"period":"2020-04-19","ratio":56.49276},{"period":"2020-04-20","ratio":37.64068},{"period":"2020-04-21","ratio":38.79299},{"period":"2020-04-22","ratio":38.73196},{"period":"2020-04-23","ratio":39.15187},{"period":"2020-04-24","ratio":42.25971},{"period":"2020-04-25","ratio":62.95622},{"period":"2020-04-26","ratio":69.86523},{"period":"2020-04-27","ratio":40.0808},{"period":"2020-04-28","ratio":42.52337},{"period":"2020-04-29","ratio":43.91982},{"period":"2020-04-30","ratio":74.35121},{"period":"2020-05-01","ratio":75.70982},{"period":"2020-05-02","ratio":76.85725},{"period":"2020-05-03","ratio":74.99938},{"period":"2020-05-04","ratio":59.82153},{"period":"2020-05-05","ratio":73.81777},{"period":"2020-05-06","ratio":39.82568},{"period":"2020-05-07","ratio":40.6594},{"period":"2020-05-08","ratio":43.00798},{"period":"2020-05-09","ratio":57.56817},{"period":"2020-05-10","ratio":63.58731},{"period":"2020-05-11","ratio":39.76465},{"period":"2020-05-12","ratio":40.66673},{"period":"2020-05-13","ratio":41.9582},{"period":"2020-05-14","ratio":40.79001},{"period":"2020-05-15","ratio":41.80561},{"period":"2020-05-16","ratio":65.20592},{"period":"2020-05-17","ratio":70.33641},{"period":"2020-05-18","ratio":39.79517},{"period":"2020-05-19","ratio":40.52513},{"period":"2020-05-20","ratio":41.62007},{"period":"2020-05-21","ratio":42.34515},{"period":"2020-05-22","ratio":44.98547},{"period":"2020-05-23","ratio":72.07465},{"period":"2020-05-24","ratio":70.26439},{"period":"2020-05-25","ratio":42.28046},{"period":"2020-05-26","ratio":41.68599},{"period":"2020-05-27","ratio":42.35614},{"period":"2020-05-28","ratio":40.58616},{"period":"2020-05-29","ratio":42.5014},{"period":"2020-05-30","ratio":66.54378},{"period":"2020-05-31","ratio":64.77136},{"period":"2020-06-01","ratio":39.74634},{"period":"2020-06-02","ratio":37.93486},{"period":"2020-06-03","ratio":39.42042},{"period":"2020-06-04","ratio":40.34691},{"period":"2020-06-05","ratio":45.95712},{"period":"2020-06-06","ratio":75.02868},{"period":"2020-06-07","ratio":73.73477},{"period":"2020-06-08","ratio":42.71135},{"period":"2020-06-09","ratio":43.49869},{"period":"2020-06-10","ratio":42.43914},{"period":"2020-06-11","ratio":42.76262},{"period":"2020-06-12","ratio":45.31017},{"period":"2020-06-13","ratio":74.38661},{"period":"2020-06-14","ratio":75.62803},{"period":"2020-06-15","ratio":44.0187},{"period":"2020-06-16","ratio":43.0922},{"period":"2020-06-17","ratio":42.47088},{"period":"2020-06-18","ratio":42.22309},{"period":"2020-06-19","ratio":46.94343},{"period":"2020-06-20","ratio":73.62613},{"period":"2020-06-21","ratio":77.68975},{"period":"2020-06-22","ratio":44.62903},{"period":"2020-06-23","ratio":44.26649},{"period":"2020-06-24","ratio":41.21115},{"period":"2020-06-25","ratio":40.7595},{"period":"2020-06-26","ratio":45.64097},{"period":"2020-06-27","ratio":72.33465},{"period":"2020-06-28","ratio":77.77886},{"period":"2020-06-29","ratio":41.17575},{"period":"2020-06-30","ratio":39.47779},{"period":"2020-07-01","ratio":41.07687},{"period":"2020-07-02","ratio":43.15202},{"period":"2020-07-03","ratio":46.51253},{"period":"2020-07-04","ratio":72.86809},{"period":"2020-07-05","ratio":74.49891},{"period":"2020-07-06","ratio":42.79924},{"period":"2020-07-07","ratio":44.36537},{"period":"2020-07-08","ratio":44.28846},{"period":"2020-07-09","ratio":43.9894},{"period":"2020-07-10","ratio":47.59161},{"period":"2020-07-11","ratio":75.93686},{"period":"2020-07-12","ratio":75.51207},{"period":"2020-07-13","ratio":41.77998},{"period":"2020-07-14","ratio":43.81728},{"period":"2020-07-15","ratio":44.76453},{"period":"2020-07-16","ratio":45.83628},{"period":"2020-07-17","ratio":49.26881},{"period":"2020-07-18","ratio":76.16635},{"period":"2020-07-19","ratio":69.00588},{"period":"2020-07-20","ratio":43.71719},{"period":"2020-07-21","ratio":47.59283},{"period":"2020-07-22","ratio":43.24235},{"period":"2020-07-23","ratio":42.92863},{"period":"2020-07-24","ratio":46.88484},{"period":"2020-07-25","ratio":77.36261},{"period":"2020-07-26","ratio":85.29088},{"period":"2020-07-27","ratio":47.50738},{"period":"2020-07-28","ratio":47.68316},{"period":"2020-07-29","ratio":46.61385},{"period":"2020-07-30","ratio":50.17455},{"period":"2020-07-31","ratio":56.69051},{"period":"2020-08-01","ratio":85.02355},{"period":"2020-08-02","ratio":82.72625},{"period":"2020-08-03","ratio":62.64373},{"period":"2020-08-04","ratio":62.76824},{"period":"2020-08-05","ratio":58.20048},{"period":"2020-08-06","ratio":53.25309},{"period":"2020-08-07","ratio":57.24591},{"period":"2020-08-08","ratio":71.41793},{"period":"2020-08-09","ratio":68.25028},{"period":"2020-08-10","ratio":49.66431},{"period":"2020-08-11","ratio":50.85569},{"period":"2020-08-12","ratio":53.20548},{"period":"2020-08-13","ratio":55.1964},{"period":"2020-08-14","ratio":61.24118},{"period":"2020-08-15","ratio":85.89634},{"period":"2020-08-16","ratio":100},{"period":"2020-08-17","ratio":85.52891},{"period":"2020-08-18","ratio":56.56478},{"period":"2020-08-19","ratio":55.71519},{"period":"2020-08-20","ratio":53.42765},{"period":"2020-08-21","ratio":51.60518},{"period":"2020-08-22","ratio":63.10148},{"period":"2020-08-23","ratio":70.33275},{"period":"2020-08-24","ratio":48.07377},{"period":"2020-08-25","ratio":47.82231},{"period":"2020-08-26","ratio":42.47088},{"period":"2020-08-27","ratio":41.77876},{"period":"2020-08-28","ratio":90.45189},{"period":"2020-08-29","ratio":74.92859},{"period":"2020-08-30","ratio":78.24271},{"period":"2020-08-31","ratio":48.69998}]}]}
  title                                      keywords  \
0   명동역  [맛집, 카페, 놀거리, 볼거리, 데이트, 나들이, 구경, 약속, 모임, 장소]

                                                data
0  [{'period': '2020-01-24', 'ratio': 44.39466}, ...

AttributeError: 'dict' object has no attribute 'encode'

In [98]:
import urllib.request

def get_trend(body):
    url = "https://openapi.naver.com/v1/datalab/search"
    client_id = "W5USlEAS7_mhRRbY_4A_"
    client_secret = "duCoBBdkM6"
    
    request = urllib.request.Request(url)
    request.add_header("X-Naver-Client-Id", client_id)
    request.add_header("X-Naver-Client-Secret", client_secret)
    request.add_header("Content-Type","application/json")
    response = urllib.request.urlopen(request, data=body.encode("utf-8"))

    return json.loads(response.read().decode('utf-8'))

naver_trend = []
for i in range(len(subway_list)):
    body = {
        "startDate":"2020-01-24",
        "endDate":"2020-08-31",
        "timeUnit":"date",
        "keywordGroups":[
            {"groupName":"{}역".format(subway_list[i]), "keywords":["{}역".format(subway_list[i])]}
#              "keywords":["맛집","카페","놀거리","볼거리","데이트","나들이","구경","약속","모임","장소"]}
        ]
    }

    body = json.dumps(body, indent=4, ensure_ascii=False)
    naver_trend.append(get_trend(body))

In [268]:
# data = json.loads(response_body)
# tmp = pd.DataFrame(data['results'])
# print(tmp)

# res = data['results'][0]['data']
# pd.DataFrame(res)

In [100]:
subway_list[-1]

'효창공원앞'

In [338]:
a = []
# df_i = []
for i in range(len(subway_list)):
    df_i = pd.DataFrame(data = (pd.DataFrame(naver_trend))['results'][i][0]['data'], columns=['period', 'ratio'])
    a.append(df_i)
a

[         period     ratio
 0    2020-01-24  40.58524
 1    2020-01-25  36.76844
 2    2020-01-26  41.73027
 3    2020-01-27  41.22137
 4    2020-01-28  57.50636
 ..          ...       ...
 216  2020-08-27  44.78371
 217  2020-08-28  48.21882
 218  2020-08-29  30.78880
 219  2020-08-30  26.97201
 220  2020-08-31  41.09414

 [221 rows x 2 columns],
          period     ratio
 0    2020-01-24  48.39483
 1    2020-01-25  46.35463
 2    2020-01-26  48.42484
 3    2020-01-27  52.86528
 4    2020-01-28  73.53735
 ..          ...       ...
 216  2020-08-27  53.16531
 217  2020-08-28  58.86588
 218  2020-08-29  39.18391
 219  2020-08-30  32.01320
 220  2020-08-31  53.37533

 [221 rows x 2 columns],
          period    ratio
 0    2020-01-24  1.18306
 1    2020-01-25  1.05410
 2    2020-01-26  1.50032
 3    2020-01-27  1.66105
 4    2020-01-28  1.99559
 ..          ...      ...
 216  2020-08-27  0.92607
 217  2020-08-28  1.12512
 218  2020-08-29  0.85692
 219  2020-08-30  0.64760
 220  2020-08-31  0.90364

 [221 rows x 2 columns],
          period    ratio
 0    2020-01-24  1.89443
 1    2020-01-25  1.49450
 2    2020-01-26  1.79971
 3    2020-01-27  2.51012
 4    2020-01-28  3.98358
 ..          ...      ...
 216  2020-08-27  2.96269
 217  2020-08-28  3.16792
 218  2020-08-29  2.34173
 219  2020-08-30  1.73130
 220  2020-08-31  2.93111

 [221 rows x 2 columns],
          period     ratio
 0    2020-01-24  48.43554
 1    2020-01-25  45.93241
 2    2020-01-26  53.44180
 3    2020-01-27  60.95118
 4    2020-01-28  70.58823
 ..          ...       ...
 216  2020-08-27  54.06758
 217  2020-08-28  65.45682
 218  2020-08-29  44.18022
 219  2020-08-30  39.79974
 220  2020-08-31  67.45932

 [221 rows x 2 columns],
          period     ratio
 0    2020-01-24  45.14767
 1    2020-01-25  42.19409
 2    2020-01-26  64.97890
 3    2020-01-27  61.60337
 4    2020-01-28  79.32489
 ..          ...       ...
 216  2020-08-27  61.60337
 217  2020-08-28  69.19831
 218  2020-08-29  61.60337
 219  2020-08-30  37.97468
 220  2020-08-31  56.54008

 [221 rows x 2 columns],
 Empty DataFrame
 Columns: [period, ratio]
 Index: [],
          period     ratio
 0    2020-01-24  20.62689
 1    2020-01-25  23.66026
 2    2020-01-26  21.43579
 3    2020-01-27  23.76137
 4    2020-01-28  31.14256
 ..          ...       ...
 216  2020-08-27  28.81698
 217  2020-08-28  22.95247
 218  2020-08-29  22.64914
 219  2020-08-30  18.40242
 220  2020-08-31  24.36804

 [221 rows x 2 columns],
          period     ratio
 0    2020-01-24  31.46067
 1    2020-01-25  44.56928
 2    2020-01-26  28.83895
 3    2020-01-27  38.57677
 4    2020-01-28  48.68913
 ..          ...       ...
 216  2020-08-27  35.58052
 217  2020-08-28  33.70786
 218  2020-08-29  37.45318
 219  2020-08-30  27.34082
 220  2020-08-31  34.45692

 [221 rows x 2 columns],
          period     ratio
 0    2020-01-24  54.90654
 1    2020-01-25  57.71028
 2    2020-01-26  63.31775
 3    2020-01-27  61.68224
 4    2020-01-28  82.94392
 ..          ...       ...
 216  2020-08-27  59.34579
 217  2020-08-28  67.05607
 218  2020-08-29  61.44859
 219  2020-08-30  52.80373
 220  2020-08-31  63.08411

 [221 rows x 2 columns],
          period      ratio
 0    2020-01-24   22.54581
 1    2020-01-25   18.95556
 2    2020-01-26   28.19482
 3    2020-01-27  100.00000
 4    2020-01-28   32.16168
 ..          ...        ...
 216  2020-08-27   14.13507
 217  2020-08-28   18.57896
 218  2020-08-29   14.71252
 219  2020-08-30   11.17248
 220  2020-08-31   13.68315

 [221 rows x 2 columns],
 Empty DataFrame
 Columns: [period, ratio]
 Index: [],
          period     ratio
 0    2020-01-24  24.47368
 1    2020-01-25  23.68421
 2    2020-01-26  30.78947
 3    2020-01-27  33.94736
 4    2020-01-28  47.10526
 ..          ...       ...
 216  2020-08-27  40.26315
 217  2020-08-28  33.94736
 218  2020-08-29  23.42105
 219  2020-08-30  18.94736
 220  2020-08-31  37.36842

 [221 rows x 2 columns],
          period     ratio
 0    2020-01-24  34.61538
 1    2020-01-25  36.05769
 2    2020-01-26  38.82211
 3    2020-01-27  36.65865
 4    2020-01-28  56.73076
 ..          ...       ...
 216  2020-08-27  48.31730
 217  2020-08-28  38.46153
 218  2020-08-29  36.41826
 219  2020-08-30  31.73076
 220  2020-08-31  47.47596

 [221 rows x 2 columns],
 Empty DataFrame
 Columns: [period, ratio]
 Index: [],
          period     ratio
 0    2020-01-24  96.51347
 1    2020-01-25  78.68462
 2    2020-01-26  91.91759
 3    2020-01-27  92.86846
 4    2020-01-28  82.25039
 ..          ...       ...
 216  2020-08-27  43.50237
 217  2020-08-28  53.88272
 218  2020-08-29  43.26465
 219  2020-08-30  34.78605
 220  2020-08-31  45.87955

 [221 rows x 2 columns],
          period     ratio
 0    2020-01-24  39.89100
 1    2020-01-25  41.58038
 2    2020-01-26  46.70299
 3    2020-01-27  47.57493
 4    2020-01-28  70.62670
 ..          ...       ...
 216  2020-08-27  50.08174
 217  2020-08-28  53.46049
 218  2020-08-29  37.16621
 219  2020-08-30  31.55313
 220  2020-08-31  47.30245

 [221 rows x 2 columns],
 Empty DataFrame
 Columns: [period, ratio]
 Index: [],
 Empty DataFrame
 Columns: [period, ratio]
 Index: [],
          period     ratio
 0    2020-01-24  74.19354
 1    2020-01-25  75.26881
 2    2020-01-26  81.29032
 3    2020-01-27  70.32258
 4    2020-01-28  82.15053
 ..          ...       ...
 216  2020-08-27  48.81720
 217  2020-08-28  57.84946
 218  2020-08-29  46.66666
 219  2020-08-30  38.06451
 220  2020-08-31  53.54838

 [221 rows x 2 columns],
 Empty DataFrame
 Columns: [period, ratio]
 Index: [],
 Empty DataFrame
 Columns: [period, ratio]
 Index: [],
 Empty DataFrame
 Columns: [period, ratio]
 Index: [],
          period     ratio
 0    2020-01-24  51.61151
 1    2020-01-25  53.58831
 2    2020-01-26  62.91362
 3    2020-01-27  55.95186
 4    2020-01-28  73.01246
 ..          ...       ...
 216  2020-08-27  46.45466
 217  2020-08-28  47.44305
 218  2020-08-29  36.31284
 219  2020-08-30  31.45681
 220  2020-08-31  40.73914

 [221 rows x 2 columns],
          period     ratio
 0    2020-01-24  46.56862
 1    2020-01-25  52.20588
 2    2020-01-26  50.24509
 3    2020-01-27  54.41176
 4    2020-01-28  89.21568
 ..          ...       ...
 216  2020-08-27  59.55882
 217  2020-08-28  56.37254
 218  2020-08-29  54.41176
 219  2020-08-30  38.48039
 220  2020-08-31  50.73529

 [221 rows x 2 columns],
        period      ratio
 0  2020-02-28  100.00000
 1  2020-03-10   55.55555,
          period     ratio
 0    2020-01-24  65.53945
 1    2020-01-25  75.52334
 2    2020-01-26  65.53945
 3    2020-01-27  78.42190
 4    2020-01-28  76.48953
 ..          ...       ...
 216  2020-08-27  63.12399
 217  2020-08-28  69.40418
 218  2020-08-29  57.16586
 219  2020-08-30  46.69887
 220  2020-08-31  58.61513

 [221 rows x 2 columns],
 Empty DataFrame
 Columns: [period, ratio]
 Index: [],
          period     ratio
 0    2020-01-24  61.47186
 1    2020-01-25  60.60606
 2    2020-01-26  82.46753
 3    2020-01-27  73.16017
 4    2020-01-28  84.84848
 ..          ...       ...
 216  2020-08-27  64.93506
 217  2020-08-28  64.28571
 218  2020-08-29  66.66666
 219  2020-08-30  38.09523
 220  2020-08-31  49.78354

 [221 rows x 2 columns],
        period      ratio
 0  2020-01-31   57.14285
 1  2020-02-03   42.85714
 2  2020-02-07   57.14285
 3  2020-02-14   42.85714
 4  2020-02-15  100.00000
 5  2020-03-07   35.71428
 6  2020-04-02   35.71428,
          period     ratio
 0    2020-01-24  52.02952
 1    2020-01-25  50.55350
 2    2020-01-26  52.76752
 3    2020-01-27  63.09963
 4    2020-01-28  71.21771
 ..          ...       ...
 216  2020-08-27  52.39852
 217  2020-08-28  64.94464
 218  2020-08-29  52.76752
 219  2020-08-30  42.06642
 220  2020-08-31  52.02952

 [221 rows x 2 columns],
          period     ratio
 0    2020-01-24  52.97029
 1    2020-01-25  55.44554
 2    2020-01-26  62.37623
 3    2020-01-27  60.64356
 4    2020-01-28  71.28712
 ..          ...       ...
 216  2020-08-27  58.16831
 217  2020-08-28  70.29702
 218  2020-08-29  52.97029
 219  2020-08-30  50.99009
 220  2020-08-31  53.96039

 [221 rows x 2 columns],
          period     ratio
 0    2020-01-24  25.78125
 1    2020-01-25  35.02604
 2    2020-01-26  27.40885
 3    2020-01-27  27.21354
 4    2020-01-28  28.97135
 ..          ...       ...
 216  2020-08-27  21.28906
 217  2020-08-28  23.37239
 218  2020-08-29  19.27083
 219  2020-08-30  14.25781
 220  2020-08-31  25.19531

 [221 rows x 2 columns],
          period     ratio
 0    2020-01-24  58.51063
 1    2020-01-25  60.33434
 2    2020-01-26  60.94224
 3    2020-01-27  59.87841
 4    2020-01-28  68.84498
 ..          ...       ...
 216  2020-08-27  54.55927
 217  2020-08-28  54.40729
 218  2020-08-29  44.22492
 219  2020-08-30  45.28875
 220  2020-08-31  57.14285

 [221 rows x 2 columns],
          period      ratio
 0    2020-01-24   24.40528
 1    2020-01-25   25.81497
 2    2020-01-26   76.69603
 3    2020-01-27  100.00000
 4    2020-01-28   57.31277
 ..          ...        ...
 216  2020-08-27   25.24229
 217  2020-08-28   30.52863
 218  2020-08-29   25.99118
 219  2020-08-30   29.47136
 220  2020-08-31   28.85462

 [221 rows x 2 columns],
          period     ratio
 0    2020-01-24  58.37563
 1    2020-01-25  60.65989
 2    2020-01-26  56.85279
 3    2020-01-27  65.22842
 4    2020-01-28  75.63451
 ..          ...       ...
 216  2020-08-27  56.34517
 217  2020-08-28  62.94416
 218  2020-08-29  51.26903
 219  2020-08-30  44.41624
 220  2020-08-31  55.07614

 [221 rows x 2 columns],
          period     ratio
 0    2020-01-24  37.24304
 1    2020-01-25  30.83434
 2    2020-01-26  34.82466
 3    2020-01-27  38.21039
 4    2020-01-28  47.40024
 ..          ...       ...
 216  2020-08-27  38.33131
 217  2020-08-28  41.83796
 218  2020-08-29  39.29866
 219  2020-08-30  32.04353
 220  2020-08-31  33.25272

 [221 rows x 2 columns],
          period     ratio
 0    2020-01-24  60.29962
 1    2020-01-25  62.54681
 2    2020-01-26  62.92134
 3    2020-01-27  56.17977
 4    2020-01-28  88.01498
 ..          ...       ...
 216  2020-08-27  70.78651
 217  2020-08-28  68.53932
 218  2020-08-29  54.68164
 219  2020-08-30  42.32209
 220  2020-08-31  85.01872

 [221 rows x 2 columns],
 Empty DataFrame
 Columns: [period, ratio]
 Index: [],
          period     ratio
 0    2020-01-24  78.44827
 1    2020-01-25  66.16379
 2    2020-01-26  57.97413
 3    2020-01-27  54.09482
 4    2020-01-28  61.85344
 ..          ...       ...
 216  2020-08-27  51.07758
 217  2020-08-28  59.48275
 218  2020-08-29  56.03448
 219  2020-08-30  43.31896
 220  2020-08-31  54.95689

 [221 rows x 2 columns],
          period     ratio
 0    2020-01-24  54.85122
 1    2020-01-25  34.79948
 2    2020-01-26  10.73738
 3    2020-01-27  10.99611
 4    2020-01-28  14.61836
 ..          ...       ...
 216  2020-08-27  11.25485
 217  2020-08-28  11.51358
 218  2020-08-29   8.02069
 219  2020-08-30   9.44372
 220  2020-08-31  12.16041

 [221 rows x 2 columns],
 Empty DataFrame
 Columns: [period, ratio]
 Index: [],
          period     ratio
 0    2020-01-24  23.32389
 1    2020-01-25  21.90745
 2    2020-01-26  25.96789
 3    2020-01-27  30.87818
 4    2020-01-28  40.03777
 ..          ...       ...
 216  2020-08-27  31.63361
 217  2020-08-28  39.75448
 218  2020-08-29  27.57318
 219  2020-08-30  18.98016
 220  2020-08-31  36.44948

 [221 rows x 2 columns],
          period     ratio
 0    2020-01-24  24.63893
 1    2020-01-25  25.30329
 2    2020-01-26  29.34719
 3    2020-01-27  27.78740
 4    2020-01-28  30.30040
 ..          ...       ...
 216  2020-08-27  19.35297
 217  2020-08-28  23.19468
 218  2020-08-29  16.98440
 219  2020-08-30  12.70941
 220  2020-08-31  17.53321

 [221 rows x 2 columns],
          period     ratio
 0    2020-01-24  44.95049
 1    2020-01-25  52.47524
 2    2020-01-26  50.69306
 3    2020-01-27  44.75247
 4    2020-01-28  54.25742
 ..          ...       ...
 216  2020-08-27  46.13861
 217  2020-08-28  55.84158
 218  2020-08-29  43.96039
 219  2020-08-30  34.45544
 220  2020-08-31  53.46534

 [221 rows x 2 columns],
          period     ratio
 0    2020-01-24  29.03225
 1    2020-01-26  35.48387
 2    2020-01-27  22.58064
 3    2020-01-28  80.64516
 4    2020-01-29  67.74193
 ..          ...       ...
 203  2020-08-26  32.25806
 204  2020-08-27  45.16129
 205  2020-08-28  35.48387
 206  2020-08-30  29.03225
 207  2020-08-31  41.93548

 [208 rows x 2 columns],
          period     ratio
 0    2020-01-24  30.85271
 1    2020-01-25  32.79069
 2    2020-01-26  41.24031
 3    2020-01-27  39.76744
 4    2020-01-28  62.32558
 ..          ...       ...
 216  2020-08-27  43.10077
 217  2020-08-28  51.16279
 218  2020-08-29  35.96899
 219  2020-08-30  26.35658
 220  2020-08-31  37.98449

 [221 rows x 2 columns],
          period     ratio
 0    2020-01-24  61.28048
 1    2020-01-25  63.71951
 2    2020-01-26  67.98780
 3    2020-01-27  57.31707
 4    2020-01-28  79.87804
 ..          ...       ...
 216  2020-08-27  55.18292
 217  2020-08-28  72.56097
 218  2020-08-29  48.47560
 219  2020-08-30  46.95121
 220  2020-08-31  59.14634

 [221 rows x 2 columns],
          period     ratio
 0    2020-01-24  65.73033
 1    2020-01-25  70.78651
 2    2020-01-26  56.17977
 3    2020-01-27  56.74157
 4    2020-01-28  84.55056
 ..          ...       ...
 216  2020-08-27  55.89887
 217  2020-08-28  69.38202
 218  2020-08-29  58.42696
 219  2020-08-30  42.69662
 220  2020-08-31  51.96629

 [221 rows x 2 columns],
          period     ratio
 0    2020-01-24  17.08776
 1    2020-01-25  20.47872
 2    2020-01-26  16.35638
 3    2020-01-27  17.15425
 4    2020-01-28  14.89361
 ..          ...       ...
 216  2020-08-27  12.50000
 217  2020-08-28  16.82180
 218  2020-08-29  12.56648
 219  2020-08-30   9.70744
 220  2020-08-31  12.83244

 [221 rows x 2 columns],
          period      ratio
 0    2020-01-24   23.17716
 1    2020-01-25   21.09835
 2    2020-01-26   25.31802
 3    2020-01-27   27.76915
 4    2020-01-28   37.48060
 ..          ...        ...
 216  2020-08-27   35.09152
 217  2020-08-28  100.00000
 218  2020-08-29   35.30871
 219  2020-08-30   24.79056
 220  2020-08-31   30.59261

 [221 rows x 2 columns],
 Empty DataFrame
 Columns: [period, ratio]
 Index: [],
          period     ratio
 0    2020-01-24  38.87468
 1    2020-01-25  39.13043
 2    2020-01-26  42.96675
 3    2020-01-27  35.03836
 4    2020-01-28  60.86956
 ..          ...       ...
 216  2020-08-27  47.05882
 217  2020-08-28  73.91304
 218  2020-08-29  61.89258
 219  2020-08-30  52.17391
 220  2020-08-31  50.89514

 [221 rows x 2 columns],
          period     ratio
 0    2020-01-24  29.05500
 1    2020-01-25  25.10578
 2    2020-01-26  28.34978
 3    2020-01-27  32.15796
 4    2020-01-28  41.18476
 ..          ...       ...
 216  2020-08-27  33.14527
 217  2020-08-28  52.32722
 218  2020-08-29  54.30183
 219  2020-08-30  33.85049
 220  2020-08-31  25.95204

 [221 rows x 2 columns],
        period  ratio
 0  2020-03-04    100,
          period     ratio
 0    2020-01-24  24.52193
 1    2020-01-25  21.70978
 2    2020-01-26  22.27221
 3    2020-01-27  28.34645
 4    2020-01-28  32.50843
 ..          ...       ...
 216  2020-08-27  27.89651
 217  2020-08-28  29.35883
 218  2020-08-29  27.67154
 219  2020-08-30  21.93475
 220  2020-08-31  42.85714

 [221 rows x 2 columns],
          period     ratio
 0    2020-01-24   3.04093
 1    2020-01-25   3.04093
 2    2020-01-26   3.27485
 3    2020-01-27   3.85964
 4    2020-01-28  10.05847
 ..          ...       ...
 216  2020-08-27   5.84795
 217  2020-08-28   5.73099
 218  2020-08-29   2.92397
 219  2020-08-30   3.85964
 220  2020-08-31   6.31578

 [221 rows x 2 columns],
          period     ratio
 0    2020-01-24  60.32608
 1    2020-01-25  69.83695
 2    2020-01-26  68.07065
 3    2020-01-27  61.95652
 4    2020-01-28  73.23369
 ..          ...       ...
 216  2020-08-27  44.15760
 217  2020-08-28  55.02717
 218  2020-08-29  48.23369
 219  2020-08-30  42.11956
 220  2020-08-31  51.49456

 [221 rows x 2 columns],
          period     ratio
 0    2020-01-24  39.00000
 1    2020-01-25  42.00000
 2    2020-01-26  53.66666
 3    2020-01-27  49.66666
 4    2020-01-28  45.00000
 ..          ...       ...
 216  2020-08-27  38.00000
 217  2020-08-28  46.33333
 218  2020-08-29  38.00000
 219  2020-08-30  27.00000
 220  2020-08-31  39.33333

 [221 rows x 2 columns],
          period     ratio
 0    2020-01-24  26.08695
 1    2020-01-25  41.30434
 2    2020-01-26  30.43478
 3    2020-01-27  30.86956
 4    2020-01-28  32.17391
 ..          ...       ...
 216  2020-08-27  33.47826
 217  2020-08-28  30.43478
 218  2020-08-29  38.26086
 219  2020-08-30  26.08695
 220  2020-08-31  30.00000

 [221 rows x 2 columns],
          period     ratio
 0    2020-01-24  34.92907
 1    2020-01-25  33.68794
 2    2020-01-26  38.47517
 3    2020-01-27  33.51063
 4    2020-01-28  40.95744
 ..          ...       ...
 216  2020-08-27  35.46099
 217  2020-08-28  45.39007
 218  2020-08-29  26.95035
 219  2020-08-30  27.12765
 220  2020-08-31  35.99290

 [221 rows x 2 columns],
          period     ratio
 0    2020-01-24  53.45997
 1    2020-01-25  49.66078
 2    2020-01-26  58.20895
 3    2020-01-27  60.37991
 4    2020-01-28  63.63636
 ..          ...       ...
 216  2020-08-27  41.38398
 217  2020-08-28  44.36906
 218  2020-08-29  36.36363
 219  2020-08-30  28.35820
 220  2020-08-31  37.17774

 [221 rows x 2 columns],
          period     ratio
 0    2020-01-24  66.46661
 1    2020-01-25  52.13803
 2    2020-01-26  75.99399
 3    2020-01-27  71.26781
 4    2020-01-28  76.44411
 ..          ...       ...
 216  2020-08-27  44.71117
 217  2020-08-28  51.38784
 218  2020-08-29  43.73593
 219  2020-08-30  32.10802
 220  2020-08-31  40.13503

 [221 rows x 2 columns],
          period     ratio
 0    2020-01-24  63.40425
 1    2020-01-25  76.17021
 2    2020-01-26  85.53191
 3    2020-01-27  59.14893
 4    2020-01-28  75.31914
 ..          ...       ...
 216  2020-08-27  44.68085
 217  2020-08-28  61.70212
 218  2020-08-29  37.87234
 219  2020-08-30  25.53191
 220  2020-08-31  41.70212

 [221 rows x 2 columns],
          period     ratio
 0    2020-01-24  43.80952
 1    2020-01-25  43.57142
 2    2020-01-26  45.95238
 3    2020-01-27  48.09523
 4    2020-01-28  55.47619
 ..          ...       ...
 216  2020-08-27  36.66666
 217  2020-08-28  39.04761
 218  2020-08-29  36.19047
 219  2020-08-30  27.61904
 220  2020-08-31  38.57142

 [221 rows x 2 columns],
 Empty DataFrame
 Columns: [period, ratio]
 Index: [],
          period     ratio
 0    2020-01-24  57.06521
 1    2020-01-25  45.10869
 2    2020-01-26  62.50000
 3    2020-01-27  57.06521
 4    2020-01-28  70.65217
 ..          ...       ...
 216  2020-08-27  55.43478
 217  2020-08-28  66.30434
 218  2020-08-29  54.34782
 219  2020-08-30  39.67391
 220  2020-08-31  53.80434

 [221 rows x 2 columns],
          period     ratio
 0    2020-01-24  51.51739
 1    2020-01-25  49.88897
 2    2020-01-26  56.92079
 3    2020-01-27  59.14137
 4    2020-01-28  78.83049
 ..          ...       ...
 216  2020-08-27  47.52035
 217  2020-08-28  47.81643
 218  2020-08-29  38.71206
 219  2020-08-30  35.23316
 220  2020-08-31  44.18948

 [221 rows x 2 columns],
          period     ratio
 0    2020-01-24  34.51851
 1    2020-01-25  30.66666
 2    2020-01-26  42.37037
 3    2020-01-27  45.77777
 4    2020-01-28  58.96296
 ..          ...       ...
 216  2020-08-27  49.18518
 217  2020-08-28  48.88888
 218  2020-08-29  34.22222
 219  2020-08-30  33.92592
 220  2020-08-31  47.25925

 [221 rows x 2 columns],
          period     ratio
 0    2020-01-24  24.63295
 1    2020-01-25  29.36378
 2    2020-01-26  29.85318
 3    2020-01-27  19.08646
 4    2020-01-28  18.76019
 ..          ...       ...
 216  2020-08-27  18.10766
 217  2020-08-28  23.32789
 218  2020-08-29  18.43393
 219  2020-08-30  21.53344
 220  2020-08-31  24.95921

 [221 rows x 2 columns],
          period     ratio

In [369]:
a[0]['period']

0      2020-01-24
1      2020-01-25
2      2020-01-26
3      2020-01-27
4      2020-01-28
          ...
216    2020-08-27
217    2020-08-28
218    2020-08-29
219    2020-08-30
220    2020-08-31
Name: period, Length: 221, dtype: object

In [353]:
len(a)

244

In [354]:
b = pd.concat([a[0], a[1], a[2], a[3], a[4], a[5], a[6], a[7], a[8], a[9], a[10], a[11], a[12], a[13], a[14], a[15], a[16], a[17], a[18], a[19], a[20], a[21], a[22], a[23], a[24], a[25], a[26], a[27], a[28], a[29], a[30], a[31], a[32], a[33], a[34], a[35], a[36], a[37], a[38], a[39], a[40], a[41], a[42], a[43], a[44], a[45], a[46], a[47], a[48], a[49], a[50], a[51], a[52], a[53], a[54], a[55], a[56], a[57], a[58], a[59], a[60], a[61], a[62], a[63], a[64], a[65], a[66], a[67], a[68], a[69], a[70], a[71], a[72], a[73], a[74], a[75], a[76], a[77], a[78], a[79], a[80], a[81], a[82], a[83], a[84], a[85], a[86], a[87], a[88], a[89], a[90], a[91], a[92], a[93], a[94], a[95], a[96], a[97], a[98], a[99], a[100], a[101], a[102], a[103], a[104], a[105], a[106], a[107], a[108], a[109], a[110], a[111], a[112], a[113], a[114], a[115], a[116], a[117], a[118], a[119], a[120], a[121], a[122], a[123], a[124], a[125], a[126], a[127], a[128], a[129], a[130], a[131], a[132], a[133], a[134], a[135], a[136], a[137], a[138], a[139], a[140], a[141], a[142], a[143], a[144], a[145], a[146], a[147], a[148], a[149], a[150], a[151], a[152], a[153], a[154], a[155], a[156], a[157], a[158], a[159], a[160], a[161], a[162], a[163], a[164], a[165], a[166], a[167], a[168], a[169], a[170], a[171], a[172], a[173], a[174], a[175], a[176], a[177], a[178], a[179], a[180], a[181], a[182], a[183], a[184], a[185], a[186], a[187], a[188], a[189], a[190], a[191], a[192], a[193], a[194], a[195], a[196], a[197], a[198], a[199], a[200], a[201], a[202], a[203], a[204], a[205], a[206], a[207], a[208], a[209], a[210], a[211], a[212], a[213], a[214], a[215], a[216], a[217], a[218], a[219], a[220], a[221], a[222], a[223], a[224], a[225], a[226], a[227], a[228], a[229], a[230], a[231], a[232], a[233],a[234],a[235],a[236],a[237],a[238],a[239],a[240],a[241],a[242],a[243]], axis=1)
b.drop(['period'], axis=1, inplace=True)

In [355]:
b.columns = subway_list
b

,가락시장,가산디지털단지,강남,강남구청,강동,강동구청,강변(동서울터미널),개롱,개화산,거여,...,한양대,합정,행당,혜화,홍대입구,홍제,화곡,화랑대(서울여대입구),회현(남대문시장),효창공원앞
0,40.58524,48.39483,1.18306,1.89443,48.43554,45.14767,NaN,20.62689,31.46067,54.90654,...,42.37288,42.78317,56.28140,60.65476,56.85497,49.57983,28.75068,NaN,NaN,23.52941
1,36.76844,46.35463,1.05410,1.49450,45.93241,42.19409,NaN,23.66026,44.56928,57.71028,...,48.02259,96.92556,61.80904,60.53571,52.09778,50.84033,35.35188,NaN,NaN,33.82352
2,41.73027,48.42484,1.50032,1.79971,53.44180,64.97890,NaN,21.43579,28.83895,63.31775,...,45.76271,100.00000,61.80904,79.46428,72.74529,52.94117,34.53355,NaN,NaN,33.82352
3,41.22137,52.86528,1.66105,2.51012,60.95118,61.60337,NaN,23.76137,38.57677,61.68224,...,41.80790,68.80258,53.26633,77.61904,70.23455,52.10084,32.62411,NaN,NaN,27.94117
4,57.50636,73.53735,1.99559,3.98358,70.58823,79.32489,NaN,31.14256,48.68913,82.94392,...,63.27683,55.21035,79.39698,69.40476,63.52824,51.96078,38.95253,NaN,NaN,69.11764
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,48.21882,58.86588,1.12512,3.16792,65.45682,69.19831,NaN,22.95247,33.70786,67.05607,...,38.41807,47.02265,54.77386,32.67857,33.36636,44.95798,34.69721,NaN,NaN,23.52941
218,30.78880,39.18391,0.85692,2.34173,44.18022,61.60337,NaN,22.64914,37.45318,61.44859,...,45.19774,34.04530,52.76381,27.02380,28.11364,38.93557,27.60501,NaN,NaN,27.94117
219,26.97201,32.01320,0.64760,1.73130,39.79974,37.97468,NaN,18.40242,27.34082,52.80373,...,23.16384,26.89320,48.74371,28.57142,21.37429,37.25490,25.15002,NaN,NaN,20.58823
220,41.09414,53.37533,0.90364,2.93111,67.45932,56.54008,NaN,24.36804,34.45692,63.08411,...,50.28248,29.93527,50.75376,27.50000,23.35645,49.71988,31.26022,NaN,NaN,36.76470
221,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [370]:
b.insert(0,"period",a[0]['period'],True)

In [54]:
b.index[0]

Timestamp('2020-01-24 00:00:00')

In [366]:
b.drop(b.index[221], axis=0, inplace=True)

In [373]:
b.to_csv('검색어트렌드.csv', index=False)

# 주별로 묶기

In [21]:
import pandas as pd
import numpy as np
b = pd.read_csv('검색어트렌드.csv')

In [26]:
type(b['period'][0])
b.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 221 entries, 0 to 220
Columns: 245 entries, period to 효창공원앞
dtypes: datetime64[ns](1), float64(244)
memory usage: 423.1 KB

In [25]:
import datetime
# b['period'].apply(lambda x: pd.to_datetime(str(x), format='%Y-%m-%d'))
b['period'] = pd.to_datetime(b['period'])

In [6]:
# # b.reset_index(inplace=True)
# from datetime import timedelta
# pd.DatetimeIndex(b['period']) + timedelta(weeks=1)

DatetimeIndex(['2020-01-31', '2020-02-01', '2020-02-02', '2020-02-03',
               '2020-02-04', '2020-02-05', '2020-02-06', '2020-02-07',
               '2020-02-08', '2020-02-09',
               ...
               '2020-08-29', '2020-08-30', '2020-08-31', '2020-09-01',
               '2020-09-02', '2020-09-03', '2020-09-04', '2020-09-05',
               '2020-09-06', '2020-09-07'],
              dtype='datetime64[ns]', name='period', length=221, freq='D')

In [11]:
# b.set_index('period', inplace=True)
# b.resample('W-SAT').mean()

In [38]:
b.columns

Index(['period', '가락시장', '가산디지털단지', '강남', '강남구청', '강동', '강동구청', '강변(동서울터미널)',
       '개롱', '개화산',
       ...
       '한양대', '합정', '행당', '혜화', '홍대입구', '홍제', '화곡', '화랑대(서울여대입구)', '회현(남대문시장)',
       '효창공원앞'],
      dtype='object', length=245)

In [45]:
pd.DataFrame(b.iloc[0:8].mean())

                     0
가락시장         55.820608
가산디지털단지      61.697414
강남            1.655382
강남구청          3.078457
강동           64.971835
...                ...
홍제           55.619744
화곡           36.640750
화랑대(서울여대입구)        NaN
회현(남대문시장)          NaN
효창공원앞        41.544113

[244 rows x 1 columns]

In [69]:
df = pd.DataFrame(data=[], columns=b.columns[:])

In [70]:
df

Empty DataFrame
Columns: [period, 가락시장, 가산디지털단지, 강남, 강남구청, 강동, 강동구청, 강변(동서울터미널), 개롱, 개화산, 거여, 건대입구, 경복궁(정부서울청사), 경찰병원, 고덕, 고려대(종암), 고속터미널, 공덕, 공릉(서울과학기술대), 광나루(장신대), 광명사거리, 광화문(세종문화회관), 광흥창(서강), 교대(법원·검찰청), 구로디지털단지, 구산, 구의(광진구청), 구파발, 군자(능동), 굴포천, 굽은다리(강동구민회관앞), 금호, 길동, 길음, 김포공항, 까치산, 까치울, 낙성대, 남구로, 남부터미널(예술의전당), 남성, 남태령, 남한산성입구(성남법원?검찰청), 내방, 노원, 녹번, 녹사평(용산구청), 논현, 단대오거리, 답십리, 당고개, 당산, 대림(구로구청), 대청, 대치, 대흥(서강대앞), 도곡, 도림천, 도봉산, 독립문, 독바위, 돌곶이, 동대문, 동대문역사문화공원, 동대입구, 동묘앞, 동작(현충원), 둔촌동, 디지털미디어시티, 뚝섬, 뚝섬유원지, 마곡, 마들, 마장, 마천, 마포, 마포구청, 망원, 매봉, 먹골, 면목, 명동, 명일, 모란, 목동, 몽촌토성(평화의문), 무악재, 문래, 문정, 미아(서울사이버대학), 미아사거리, 반포, 발산, 방배, 방이, 방화, 버티고개, 보라매, 보문, 복정, ...]
Index: []

[0 rows x 245 columns]

In [65]:
(b.iloc[:8]).mean()

가락시장           55.820608
가산디지털단지        61.697414
강남              1.655382
강남구청            3.078457
강동             64.971835
                 ...
홍제             55.619744
화곡             36.640750
화랑대(서울여대입구)          NaN
회현(남대문시장)            NaN
효창공원앞          41.544113
Length: 244, dtype: float64

In [72]:
# df = pd.DataFrame(data=[], columns=b.columns)
from tqdm import tqdm
for i in tqdm(range(len(b))):
    df = df.append(pd.DataFrame(data=[b.iloc[i:i+8].mean()], columns=b.columns))
df

100%|████████████████████████████████████████████████████████████████████████████████| 221/221 [00:09<00:00, 24.45it/s]

,period,가락시장,가산디지털단지,강남,강남구청,강동,강동구청,강변(동서울터미널),개롱,개화산,...,한양대,합정,행당,혜화,홍대입구,홍제,화곡,화랑대(서울여대입구),회현(남대문시장),효창공원앞
0,NaN,55.820608,61.697414,1.655382,3.078457,64.971835,71.729952,NaN,27.110714,39.232204,...,57.062141,68.438508,65.703513,72.336305,63.709939,55.619744,36.640750,NaN,NaN,41.544113
0,NaN,57.665391,62.751270,1.735865,3.331707,67.850434,75.685649,NaN,27.944890,39.840818,...,58.686435,71.670708,66.017583,74.940471,66.893784,57.668062,37.384066,NaN,NaN,47.242641
0,NaN,58.078877,62.529998,1.751400,3.444847,69.055065,77.162441,NaN,27.654192,37.874526,...,58.898300,67.459542,62.939693,75.208329,67.686649,56.285010,36.599832,NaN,NaN,45.772054
0,NaN,59.653305,65.125256,1.755488,3.756640,71.151435,80.643454,NaN,28.526285,39.044938,...,60.310729,60.857600,64.195974,75.334817,64.461507,56.617644,36.913525,NaN,NaN,48.161760
0,NaN,61.545799,67.176711,1.739951,3.969765,72.731535,83.966239,NaN,28.854900,39.559919,...,60.875701,58.260513,64.949742,76.510413,61.723649,57.370444,37.697759,NaN,NaN,50.735290
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,NaN,38.371496,47.320726,0.891870,2.626950,54.192736,57.383962,NaN,23.437810,33.707860,...,40.112990,36.802584,52.261298,28.976186,26.296656,42.408960,29.383516,NaN,NaN,31.176466
0,NaN,36.768442,45.859580,0.883320,2.543015,54.224025,56.329110,NaN,22.093018,33.239695,...,39.265532,34.474105,51.758785,28.943448,26.552685,42.717082,29.678115,NaN,NaN,27.205877
0,NaN,32.951650,41.524147,0.802720,2.334713,50.479760,52.039377,NaN,21.806533,33.083640,...,39.548020,30.291257,50.753760,27.698407,24.281460,41.970117,28.005083,NaN,NaN,28.431367
0,NaN,34.033075,42.694265,0.775620,2.331205,53.629530,47.257380,NaN,21.385230,30.898870,...,36.723160,28.414235,49.748735,28.035710,22.365370,43.487390,28.205120,NaN,NaN,28.676465
0,NaN,41.094140,53.375330,0.903640,2.931110,67.459320,56.540080,NaN,24.368040,34.456920,...,50.282480,29.935270,50.753760,27.500000,23.356450,49.719880,31.260220,NaN,NaN,36.764700

In [79]:
df

,level_0,index,period,가락시장,가산디지털단지,강남,강남구청,강동,강동구청,강변(동서울터미널),...,한양대,합정,행당,혜화,홍대입구,홍제,화곡,화랑대(서울여대입구),회현(남대문시장),효창공원앞
0,0,0,NaN,55.820608,61.697414,1.655382,3.078457,64.971835,71.729952,NaN,...,57.062141,68.438508,65.703513,72.336305,63.709939,55.619744,36.640750,NaN,NaN,41.544113
1,1,0,NaN,57.665391,62.751270,1.735865,3.331707,67.850434,75.685649,NaN,...,58.686435,71.670708,66.017583,74.940471,66.893784,57.668062,37.384066,NaN,NaN,47.242641
2,2,0,NaN,58.078877,62.529998,1.751400,3.444847,69.055065,77.162441,NaN,...,58.898300,67.459542,62.939693,75.208329,67.686649,56.285010,36.599832,NaN,NaN,45.772054
3,3,0,NaN,59.653305,65.125256,1.755488,3.756640,71.151435,80.643454,NaN,...,60.310729,60.857600,64.195974,75.334817,64.461507,56.617644,36.913525,NaN,NaN,48.161760
4,4,0,NaN,61.545799,67.176711,1.739951,3.969765,72.731535,83.966239,NaN,...,60.875701,58.260513,64.949742,76.510413,61.723649,57.370444,37.697759,NaN,NaN,50.735290
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,216,0,NaN,38.371496,47.320726,0.891870,2.626950,54.192736,57.383962,NaN,...,40.112990,36.802584,52.261298,28.976186,26.296656,42.408960,29.383516,NaN,NaN,31.176466
217,217,0,NaN,36.768442,45.859580,0.883320,2.543015,54.224025,56.329110,NaN,...,39.265532,34.474105,51.758785,28.943448,26.552685,42.717082,29.678115,NaN,NaN,27.205877
218,218,0,NaN,32.951650,41.524147,0.802720,2.334713,50.479760,52.039377,NaN,...,39.548020,30.291257,50.753760,27.698407,24.281460,41.970117,28.005083,NaN,NaN,28.431367
219,219,0,NaN,34.033075,42.694265,0.775620,2.331205,53.629530,47.257380,NaN,...,36.723160,28.414235,49.748735,28.035710,22.365370,43.487390,28.205120,NaN,NaN,28.676465
220,220,0,NaN,41.094140,53.375330,0.903640,2.931110,67.459320,56.540080,NaN,...,50.282480,29.935270,50.753760,27.500000,23.356450,49.719880,31.260220,NaN,NaN,36.764700

In [81]:
# df.reset_index(inplace=True)
df.drop(['level_0'], axis=1, inplace=True)
df.drop(['index'], axis=1, inplace=True)
df

,period,가락시장,가산디지털단지,강남,강남구청,강동,강동구청,강변(동서울터미널),개롱,개화산,...,한양대,합정,행당,혜화,홍대입구,홍제,화곡,화랑대(서울여대입구),회현(남대문시장),효창공원앞
0,NaN,55.820608,61.697414,1.655382,3.078457,64.971835,71.729952,NaN,27.110714,39.232204,...,57.062141,68.438508,65.703513,72.336305,63.709939,55.619744,36.640750,NaN,NaN,41.544113
1,NaN,57.665391,62.751270,1.735865,3.331707,67.850434,75.685649,NaN,27.944890,39.840818,...,58.686435,71.670708,66.017583,74.940471,66.893784,57.668062,37.384066,NaN,NaN,47.242641
2,NaN,58.078877,62.529998,1.751400,3.444847,69.055065,77.162441,NaN,27.654192,37.874526,...,58.898300,67.459542,62.939693,75.208329,67.686649,56.285010,36.599832,NaN,NaN,45.772054
3,NaN,59.653305,65.125256,1.755488,3.756640,71.151435,80.643454,NaN,28.526285,39.044938,...,60.310729,60.857600,64.195974,75.334817,64.461507,56.617644,36.913525,NaN,NaN,48.161760
4,NaN,61.545799,67.176711,1.739951,3.969765,72.731535,83.966239,NaN,28.854900,39.559919,...,60.875701,58.260513,64.949742,76.510413,61.723649,57.370444,37.697759,NaN,NaN,50.735290
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,NaN,38.371496,47.320726,0.891870,2.626950,54.192736,57.383962,NaN,23.437810,33.707860,...,40.112990,36.802584,52.261298,28.976186,26.296656,42.408960,29.383516,NaN,NaN,31.176466
217,NaN,36.768442,45.859580,0.883320,2.543015,54.224025,56.329110,NaN,22.093018,33.239695,...,39.265532,34.474105,51.758785,28.943448,26.552685,42.717082,29.678115,NaN,NaN,27.205877
218,NaN,32.951650,41.524147,0.802720,2.334713,50.479760,52.039377,NaN,21.806533,33.083640,...,39.548020,30.291257,50.753760,27.698407,24.281460,41.970117,28.005083,NaN,NaN,28.431367
219,NaN,34.033075,42.694265,0.775620,2.331205,53.629530,47.257380,NaN,21.385230,30.898870,...,36.723160,28.414235,49.748735,28.035710,22.365370,43.487390,28.205120,NaN,NaN,28.676465
220,NaN,41.094140,53.375330,0.903640,2.931110,67.459320,56.540080,NaN,24.368040,34.456920,...,50.282480,29.935270,50.753760,27.500000,23.356450,49.719880,31.260220,NaN,NaN,36.764700

In [94]:
import pandas

dt_index = pandas.date_range(start='2020-02-01', end='2020-09-08')
# pandas.date_range(start='20160901', end='20161031',freq='W-MON')

# type(dt_index) => DatetimeIndex
# DatetimeIndex => list(str)
dt_list = dt_index.strftime("%Y-%m-%d").tolist()

for i in dt_list:
    print(i)

2020-02-01
2020-02-02
2020-02-03
2020-02-04
2020-02-05
2020-02-06
2020-02-07
2020-02-08
2020-02-09
2020-02-10
2020-02-11
2020-02-12
2020-02-13
2020-02-14
2020-02-15
2020-02-16
2020-02-17
2020-02-18
2020-02-19
2020-02-20
2020-02-21
2020-02-22
2020-02-23
2020-02-24
2020-02-25
2020-02-26
2020-02-27
2020-02-28
2020-02-29
2020-03-01
2020-03-02
2020-03-03
2020-03-04
2020-03-05
2020-03-06
2020-03-07
2020-03-08
2020-03-09
2020-03-10
2020-03-11
2020-03-12
2020-03-13
2020-03-14
2020-03-15
2020-03-16
2020-03-17
2020-03-18
2020-03-19
2020-03-20
2020-03-21
2020-03-22
2020-03-23
2020-03-24
2020-03-25
2020-03-26
2020-03-27
2020-03-28
2020-03-29
2020-03-30
2020-03-31
2020-04-01
2020-04-02
2020-04-03
2020-04-04
2020-04-05
2020-04-06
2020-04-07
2020-04-08
2020-04-09
2020-04-10
2020-04-11
2020-04-12
2020-04-13
2020-04-14
2020-04-15
2020-04-16
2020-04-17
2020-04-18
2020-04-19
2020-04-20
2020-04-21
2020-04-22
2020-04-23
2020-04-24
2020-04-25
2020-04-26
2020-04-27
2020-04-28
2020-04-29
2020-04-30
2020-05-01
2020-05-02
2020-05-03
2020-05-04
2020-05-05
2020-05-06
2020-05-07
2020-05-08
2020-05-09
2020-05-10
2020-05-11
2020-05-12
2020-05-13
2020-05-14
2020-05-15
2020-05-16
2020-05-17
2020-05-18
2020-05-19
2020-05-20
2020-05-21
2020-05-22
2020-05-23
2020-05-24
2020-05-25
2020-05-26
2020-05-27
2020-05-28
2020-05-29
2020-05-30
2020-05-31
2020-06-01
2020-06-02
2020-06-03
2020-06-04
2020-06-05
2020-06-06
2020-06-07
2020-06-08
2020-06-09
2020-06-10
2020-06-11
2020-06-12
2020-06-13
2020-06-14
2020-06-15
2020-06-16
2020-06-17
2020-06-18
2020-06-19
2020-06-20
2020-06-21
2020-06-22
2020-06-23
2020-06-24
2020-06-25
2020-06-26
2020-06-27
2020-06-28
2020-06-29
2020-06-30
2020-07-01
2020-07-02
2020-07-03
2020-07-04
2020-07-05
2020-07-06
2020-07-07
2020-07-08
2020-07-09
2020-07-10
2020-07-11
2020-07-12
2020-07-13
2020-07-14
2020-07-15
2020-07-16
2020-07-17
2020-07-18
2020-07-19
2020-07-20
2020-07-21
2020-07-22
2020-07-23
2020-07-24
2020-07-25
2020-07-26
2020-07-27
2020-07-28
2020-07-29
2020-07-30
2020-07-31
2020-08-01
2020-08-02
2020-08-03
2020-08-04
2020-08-05
2020-08-06
2020-08-07
2020-08-08
2020-08-09
2020-08-10
2020-08-11
2020-08-12
2020-08-13
2020-08-14
2020-08-15
2020-08-16
2020-08-17
2020-08-18
2020-08-19
2020-08-20
2020-08-21
2020-08-22
2020-08-23
2020-08-24
2020-08-25
2020-08-26
2020-08-27
2020-08-28
2020-08-29
2020-08-30
2020-08-31
2020-09-01
2020-09-02
2020-09-03
2020-09-04
2020-09-05
2020-09-06
2020-09-07
2020-09-08

In [96]:
len(dt_list)

221

In [100]:
df.index[213:]

RangeIndex(start=213, stop=221, step=1)

In [104]:
# df['period'] = dt_list
# df.drop(df.index[213:], inplace=True)

In [106]:
df.to_csv('검색어트렌드.csv', index=False)
pd.read_csv('검색어트렌드.csv')

,period,가락시장,가산디지털단지,강남,강남구청,강동,강동구청,강변(동서울터미널),개롱,개화산,...,한양대,합정,행당,혜화,홍대입구,홍제,화곡,화랑대(서울여대입구),회현(남대문시장),효창공원앞
0,2020-02-01,55.820607,61.697414,1.655382,3.078458,64.971835,71.729952,NaN,27.110714,39.232204,...,57.062141,68.438508,65.703513,72.336305,63.709939,55.619744,36.640750,NaN,NaN,41.544112
1,2020-02-02,57.665391,62.751270,1.735865,3.331707,67.850434,75.685649,NaN,27.944890,39.840818,...,58.686435,71.670707,66.017582,74.940471,66.893784,57.668062,37.384066,NaN,NaN,47.242641
2,2020-02-03,58.078878,62.529998,1.751400,3.444847,69.055065,77.162441,NaN,27.654193,37.874526,...,58.898300,67.459542,62.939693,75.208329,67.686649,56.285010,36.599832,NaN,NaN,45.772054
3,2020-02-04,59.653305,65.125256,1.755488,3.756640,71.151435,80.643454,NaN,28.526285,39.044938,...,60.310729,60.857600,64.195974,75.334817,64.461507,56.617644,36.913525,NaN,NaN,48.161760
4,2020-02-05,61.545799,67.176711,1.739951,3.969765,72.731535,83.966239,NaN,28.854900,39.559919,...,60.875701,58.260512,64.949742,76.510413,61.723649,57.370444,37.697759,NaN,NaN,50.735290
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,2020-08-27,43.384219,55.265522,1.066246,3.035701,61.342299,64.135018,NaN,27.300299,38.389508,...,53.389826,35.849509,65.263815,34.672614,33.696725,47.321425,35.242766,NaN,NaN,38.235291
209,2020-08-28,43.225186,54.080404,1.017886,2.927824,59.637043,61.972570,NaN,27.199186,36.797747,...,50.282481,36.375399,63.379393,32.499995,31.677399,46.288513,34.219853,NaN,NaN,40.257350
210,2020-08-29,42.938926,53.187814,1.012221,2.888356,59.621399,60.812233,NaN,26.504039,36.048684,...,47.881351,37.322001,62.123110,31.339281,31.111656,45.885851,34.485810,NaN,NaN,39.338233
211,2020-08-30,40.139944,49.902485,0.965321,2.730486,56.523776,59.704637,NaN,25.644585,35.112354,...,46.822030,36.343036,61.180899,29.955353,29.777828,44.555319,33.421980,NaN,NaN,37.132350
212,2020-08-31,39.106229,48.511096,0.914041,2.646289,54.677718,58.175101,NaN,24.797770,34.269658,...,44.491522,35.149671,59.987431,29.486603,28.245783,43.504899,32.780954,NaN,NaN,35.110291