In [1]:
import requests
from bs4 import BeautifulSoup
import re
import pandas as pd

In [5]:
pages = [1, 2, 3, 4, 5]
url = 'http://www.weather.go.kr/weather/climate/past_cal.jsp?stn=108&yy=2020&mm={}&obs=1'.format(pages[0])

resp = requests.get(url)
soup = BeautifulSoup(resp.content, 'lxml')
tag = soup.select('tr td.align_left')
tag

[<td class="align_left"> </td>,
 <td class="align_left"> </td>,
 <td class="align_left"> </td>,
 <td class="align_left">1일</td>,
 <td class="align_left">2일</td>,
 <td class="align_left">3일</td>,
 <td class="align_left">4일</td>,
 <td class="align_left"> </td>,
 <td class="align_left"> </td>,
 <td class="align_left"> </td>,
 <td class="align_left">평균기온:-2.2℃<br/>최고기온:0.3℃<br/>최저기온:-6.5℃<br/>평균운량:8.9<br/>일강수량:0.1mm<br/></td>,
 <td class="align_left">평균기온:1.0℃<br/>최고기온:3.8℃<br/>최저기온:-0.7℃<br/>평균운량:7.9<br/>일강수량: - <br/></td>,
 <td class="align_left">평균기온:-0.1℃<br/>최고기온:4.6℃<br/>최저기온:-3.4℃<br/>평균운량:0.0<br/>일강수량: - <br/></td>,
 <td class="align_left">평균기온:1.2℃<br/>최고기온:6.1℃<br/>최저기온:-2.8℃<br/>평균운량:2.1<br/>일강수량: - <br/></td>,
 <td class="align_left">5일</td>,
 <td class="align_left">6일</td>,
 <td class="align_left">7일</td>,
 <td class="align_left">8일</td>,
 <td class="align_left">9일</td>,
 <td class="align_left">10일</td>,
 <td class="align_left">11일</td>,
 <td class="align_left">평균기온:1.3℃<br/>최고기온:6.6℃<br/>최저기온:-3.2℃<br/>평균운량:3.9<br/>일강수량: - <br/></td>,
 <td class="align_left">평균기온:3.1℃<br/>최고기온:4.6℃<br/>최저기온:0.6℃<br/>평균운량:9.8<br/>일강수량:1.8mm<br/></td>,
 <td class="align_left">평균기온:6.3℃<br/>최고기온:7.7℃<br/>최저기온:4.2℃<br/>평균운량:10.0<br/>일강수량:46.3mm<br/></td>,
 <td class="align_left">평균기온:2.4℃<br/>최고기온:8.9℃<br/>최저기온:-0.4℃<br/>평균운량:9.6<br/>일강수량:11.6mm<br/></td>,
 <td class="align_left">평균기온:-1.2℃<br/>최고기온:2.0℃<br/>최저기온:-3.1℃<br/>평균운량:1.6<br/>일강수량: - <br/></td>,
 <td class="align_left">평균기온:-0.6℃<br/>최고기온:4.2℃<br/>최저기온:-4.3℃<br/>평균운량:3.1<br/>일강수량: - <br/></td>,
 <td class="align_left">평균기온:-0.1℃<br/>최고기온:3.9℃<br/>최저기온:-2.6℃<br/>평균운량:3.6<br/>일강수량: - <br/></td>,
 <td class="align_left">12일</td>,
 <td class="align_left">13일</td>,
 <td class="align_left">14일</td>,
 <td class="align_left">15일</td>,
 <td class="align_left">16일</td>,
 <td class="align_left">17일</td>,
 <td class="align_left">18일</td>,
 <td class="align_left">평균기온:-1.0℃<br/>최고기온:2.8℃<br/>최저기온:-3.5℃<br/>평균운량:3.6<br/>일강수량: - <br/></td>,
 <td class="align_left">평균기온:-2.9℃<br/>최고기온:0.2℃<br/>최저기온:-4.7℃<br/>평균운량:1.4<br/>일강수량: - <br/></td>,
 <td class="align_left">평균기온:-2.3℃<br/>최고기온:2.6℃<br/>최저기온:-5.7℃<br/>평균운량:1.0<br/>일강수량: - <br/></td>,
 <td class="align_left">평균기온:-2.7℃<br/>최고기온:2.2℃<br/>최저기온:-6.4℃<br/>평균운량:0.1<br/>일강수량: - <br/></td>,
 <td class="align_left">평균기온:-1.7℃<br/>최고기온:3.2℃<br/>최저기온:-5.5℃<br/>평균운량:5.0<br/>일강수량: - <br/></td>,
 <td class="align_left">평균기온:-0.6℃<br/>최고기온:4.9℃<br/>최저기온:-4.8℃<br/>평균운량:4.8<br/>일강수량: - <br/></td>,
 <td class="align_left">평균기온:0.3℃<br/>최고기온:5.9℃<br/>최저기온:-4.1℃<br/>평균운량:2.1<br/>일강수량: - <br/></td>,
 <td class="align_left">19일</td>,
 <td class="align_left">20일</td>,
 <td class="align_left">21일</td>,
 <td class="align_left">22일</td>,
 <td class="align_left">23일</td>,
 <td class="align_left">24일</td>,
 <td class="align_left">25일</td>,
 <td class="align_left">평균기온:1.9℃<br/>최고기온:5.3℃<br/>최저기온:-0.4℃<br/>평균운량:4.8<br/>일강수량:0.6mm<br/></td>,
 <td class="align_left">평균기온:0.7℃<br/>최고기온:5.5℃<br/>최저기온:-3.3℃<br/>평균운량:2.3<br/>일강수량: - <br/></td>,
 <td class="align_left">평균기온:-0.4℃<br/>최고기온:5.5℃<br/>최저기온:-5.6℃<br/>평균운량:2.9<br/>일강수량: - <br/></td>,
 <td class="align_left">평균기온:3.0℃<br/>최고기온:7.8℃<br/>최저기온:-0.1℃<br/>평균운량:7.8<br/>일강수량: - <br/></td>,
 <td class="align_left">평균기온:4.6℃<br/>최고기온:9.9℃<br/>최저기온:0.0℃<br/>평균운량:3.4<br/>일강수량: - <br/></td>,
 <td class="align_left">평균기온:2.8℃<br/>최고기온:7.4℃<br/>최저기온:-1.3℃<br/>평균운량:3.0<br/>일강수량: - <br/></td>,
 <td class="align_left">평균기온:4.3℃<br/>최고기온:8.8℃<br/>최저기온:0.6℃<br/>평균운량:7.4<br/>일강수량: - <br/></td>,
 <td class="align_left">26일</td>,
 <td class="align_left">27일</td>,
 <td class="align_left">28일</td>,
 <td class="align_left">29일</td>,
 <td class="align_left">30일</td>,
 <td class="align_left">31일</td>,
 <td class="align_left"> </td>,
 <td class="align_left">평균기온:5.5℃<br/>최고기온:11.9℃<br/>최저기온:-0.2℃<br/>평균운량:5.8<br/>일강수량: - <br/></td>,
 <td class="align_left">평균기온:5.9℃<br/>최고기온:7.5℃<br/>최저기온:4.8℃<br/>평균운량:9.5<br/>일강수량:0.1mm<br/></td>,
 <td class="align_left">평균기온:6.8℃<br/>최고기온:9.9℃<br/>최저기온:4.3℃<br/>평균운량:7.3<br/>일강수량:0.0mm<br/></td>,
 <td class="align_left">평균기온:6.0℃<br/>최고기온:9.6℃<br/>최저기온:3.2℃<br/>평균운량:6.6<br/>일강수량: - <br/></td>,
 <td class="align_left">평균기온:5.2℃<br/>최고기온:10.4℃<br/>최저기온:1.4℃<br/>평균운량:4.0<br/>일강수량: - <br/></td>,
 <td class="align_left">평균기온:3.9℃<br/>최고기온:8.9℃<br/>최저기온:1.4℃<br/>평균운량:4.8<br/>일강수량:0.0mm<br/></td>,
 <td class="align_left"> </td>]

In [13]:
tag_li = []
for i in range(len(tag)):
    tag_li.append(tag[i].text)

In [18]:
while '\xa0' in tag_li:    
    tag_li.remove('\xa0') # '\xa0' 삭제
tag_li

['1일',
 '2일',
 '3일',
 '4일',
 '평균기온:-2.2℃최고기온:0.3℃최저기온:-6.5℃평균운량:8.9일강수량:0.1mm',
 '평균기온:1.0℃최고기온:3.8℃최저기온:-0.7℃평균운량:7.9일강수량: - ',
 '평균기온:-0.1℃최고기온:4.6℃최저기온:-3.4℃평균운량:0.0일강수량: - ',
 '평균기온:1.2℃최고기온:6.1℃최저기온:-2.8℃평균운량:2.1일강수량: - ',
 '5일',
 '6일',
 '7일',
 '8일',
 '9일',
 '10일',
 '11일',
 '평균기온:1.3℃최고기온:6.6℃최저기온:-3.2℃평균운량:3.9일강수량: - ',
 '평균기온:3.1℃최고기온:4.6℃최저기온:0.6℃평균운량:9.8일강수량:1.8mm',
 '평균기온:6.3℃최고기온:7.7℃최저기온:4.2℃평균운량:10.0일강수량:46.3mm',
 '평균기온:2.4℃최고기온:8.9℃최저기온:-0.4℃평균운량:9.6일강수량:11.6mm',
 '평균기온:-1.2℃최고기온:2.0℃최저기온:-3.1℃평균운량:1.6일강수량: - ',
 '평균기온:-0.6℃최고기온:4.2℃최저기온:-4.3℃평균운량:3.1일강수량: - ',
 '평균기온:-0.1℃최고기온:3.9℃최저기온:-2.6℃평균운량:3.6일강수량: - ',
 '12일',
 '13일',
 '14일',
 '15일',
 '16일',
 '17일',
 '18일',
 '평균기온:-1.0℃최고기온:2.8℃최저기온:-3.5℃평균운량:3.6일강수량: - ',
 '평균기온:-2.9℃최고기온:0.2℃최저기온:-4.7℃평균운량:1.4일강수량: - ',
 '평균기온:-2.3℃최고기온:2.6℃최저기온:-5.7℃평균운량:1.0일강수량: - ',
 '평균기온:-2.7℃최고기온:2.2℃최저기온:-6.4℃평균운량:0.1일강수량: - ',
 '평균기온:-1.7℃최고기온:3.2℃최저기온:-5.5℃평균운량:5.0일강수량: - ',
 '평균기온:-0.6℃최고기온:4.9℃최저기온:-4.8℃평균운량:4.8일강수량: - ',
 '평균기온:0.3℃최고기온:5.9℃최저기온:-4.1℃평균운량:2.1일강수량: - ',
 '19일',
 '20일',
 '21일',
 '22일',
 '23일',
 '24일',
 '25일',
 '평균기온:1.9℃최고기온:5.3℃최저기온:-0.4℃평균운량:4.8일강수량:0.6mm',
 '평균기온:0.7℃최고기온:5.5℃최저기온:-3.3℃평균운량:2.3일강수량: - ',
 '평균기온:-0.4℃최고기온:5.5℃최저기온:-5.6℃평균운량:2.9일강수량: - ',
 '평균기온:3.0℃최고기온:7.8℃최저기온:-0.1℃평균운량:7.8일강수량: - ',
 '평균기온:4.6℃최고기온:9.9℃최저기온:0.0℃평균운량:3.4일강수량: - ',
 '평균기온:2.8℃최고기온:7.4℃최저기온:-1.3℃평균운량:3.0일강수량: - ',
 '평균기온:4.3℃최고기온:8.8℃최저기온:0.6℃평균운량:7.4일강수량: - ',
 '26일',
 '27일',
 '28일',
 '29일',
 '30일',
 '31일',
 '평균기온:5.5℃최고기온:11.9℃최저기온:-0.2℃평균운량:5.8일강수량: - ',
 '평균기온:5.9℃최고기온:7.5℃최저기온:4.8℃평균운량:9.5일강수량:0.1mm',
 '평균기온:6.8℃최고기온:9.9℃최저기온:4.3℃평균운량:7.3일강수량:0.0mm',
 '평균기온:6.0℃최고기온:9.6℃최저기온:3.2℃평균운량:6.6일강수량: - ',
 '평균기온:5.2℃최고기온:10.4℃최저기온:1.4℃평균운량:4.0일강수량: - ',
 '평균기온:3.9℃최고기온:8.9℃최저기온:1.4℃평균운량:4.8일강수량:0.0mm']

In [28]:
# # Python 샘플 코드 #
# from urllib.request import Request, urlopen
# # from urllib import urlencode, quote_plus
# from urllib.parse import urlencode, quote_plus

# url = urlopen('http://apis.data.go.kr/1360000/AsosHourlyInfoService/getWthrDataList')
# queryParams = '?' + urlencode({ quote_plus('ServiceKey') : '366pqSxoNBjkXpIR7BHtAMpbhtSHkK%2BypIZpIJfazzpiYR0x08HoyFNS8kXcwgVj7eDonUl2vrib765rsYglPQ%3D%3D', quote_plus('ServiceKey') : '-', quote_plus('pageNo') : '1', quote_plus('numOfRows') : '10', quote_plus('dataType') : 'XML', quote_plus('dataCd') : 'ASOS', quote_plus('dateCd') : 'HR', quote_plus('startDt') : '20100101', quote_plus('startHh') : '01', quote_plus('endDt') : '20100601', quote_plus('endHh') : '01', quote_plus('stnIds') : '108' })

# request = Request(url + queryParams)
# request.get_method = lambda: 'GET'
# response_body = urlopen(request).read()
# print(response_body)

# 날씨데이터 (다운로드)

In [48]:
weather = pd.read_csv('날씨데이터(기상자료개방포털).csv', encoding='cp949')

In [49]:
weather = weather[['일시', '기온(°C)', '강수량(mm)', '풍속(m/s)', '습도(%)']]
weather.columns = ['date', '기온(°C)', '강수량(mm)', '풍속(m/s)', '습도(%)']

In [50]:
import datetime
weather['date'] = pd.to_datetime(weather['date'])

In [51]:
weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5856 entries, 0 to 5855
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date     5856 non-null   datetime64[ns]
 1   기온(°C)   5855 non-null   float64
 2   강수량(mm)  865 non-null    float64
 3   풍속(m/s)  5856 non-null   float64
 4   습도(%)    5856 non-null   int64
dtypes: datetime64[ns](1), float64(3), int64(1)
memory usage: 228.9 KB

In [56]:
# weather['시간'] = ''
for i in range(len(weather)):
#     weather['시간'][i] = weather['date'][i].hour
    weather['date'][i] = weather['date'][i].date()

C:\Users\jejec\anaconda3\envs\mulcam\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [57]:
# 전체 데이터프레임도 시간 앞 숫자 따서 변경할 것!
weather

           date  기온(°C)  강수량(mm)  풍속(m/s)  습도(%)  시간
0    2020-01-01    -6.5      0.0      0.0     38   0
1    2020-01-01    -5.9      NaN      1.7     40   1
2    2020-01-01    -5.7      NaN      0.1     42   2
3    2020-01-01    -5.6      0.0      0.0     46   3
4    2020-01-01    -5.4      NaN      0.0     50   4
...         ...     ...      ...      ...    ...  ..
5851 2020-08-31    28.0      NaN      3.5     73  19
5852 2020-08-31    27.6      NaN      2.5     73  20
5853 2020-08-31    27.1      NaN      2.4     74  21
5854 2020-08-31    26.8      NaN      2.3     76  22
5855 2020-08-31    26.6      NaN      2.9     74  23

[5856 rows x 6 columns]

In [58]:
weather = weather[['date', '시간', '기온(°C)', '강수량(mm)', '풍속(m/s)', '습도(%)']]
weather

           date  시간  기온(°C)  강수량(mm)  풍속(m/s)  습도(%)
0    2020-01-01   0    -6.5      0.0      0.0     38
1    2020-01-01   1    -5.9      NaN      1.7     40
2    2020-01-01   2    -5.7      NaN      0.1     42
3    2020-01-01   3    -5.6      0.0      0.0     46
4    2020-01-01   4    -5.4      NaN      0.0     50
...         ...  ..     ...      ...      ...    ...
5851 2020-08-31  19    28.0      NaN      3.5     73
5852 2020-08-31  20    27.6      NaN      2.5     73
5853 2020-08-31  21    27.1      NaN      2.4     74
5854 2020-08-31  22    26.8      NaN      2.3     76
5855 2020-08-31  23    26.6      NaN      2.9     74

[5856 rows x 6 columns]

In [64]:
weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5856 entries, 0 to 5855
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date     5856 non-null   datetime64[ns]
 1   시간       5856 non-null   object
 2   기온(°C)   5855 non-null   float64
 3   강수량(mm)  865 non-null    float64
 4   풍속(m/s)  5856 non-null   float64
 5   습도(%)    5856 non-null   int64
dtypes: datetime64[ns](1), float64(3), int64(1), object(1)
memory usage: 274.6+ KB

In [65]:
weather['강수량(mm)'] = weather['강수량(mm)'].fillna(0)
weather[weather['기온(°C)'].isnull()]

           date  시간  기온(°C)  강수량(mm)  풍속(m/s)  습도(%)
5725 2020-08-26  13     NaN      0.0      4.3     60

In [69]:
weather[5720:5730]

           date  시간  기온(°C)  강수량(mm)  풍속(m/s)  습도(%)
5720 2020-08-26   8    28.6      0.0      2.7     79
5721 2020-08-26   9    29.7      0.0      3.2     74
5722 2020-08-26  10    31.4      0.0      3.5     67
5723 2020-08-26  11    32.6      0.0      3.8     62
5724 2020-08-26  12    33.3      0.0      3.0     60
5725 2020-08-26  13     NaN      0.0      4.3     60
5726 2020-08-26  14    34.1      0.0      4.0     58
5727 2020-08-26  15    33.5      0.0      3.1     57
5728 2020-08-26  16    34.4      0.0      4.6     54
5729 2020-08-26  17    33.4      0.0      4.5     54

In [70]:
weather['기온(°C)'] = weather['기온(°C)'].fillna(method='ffill')

In [74]:
weather.isna().sum()

date       0
시간         0
기온(°C)     0
강수량(mm)    0
풍속(m/s)    0
습도(%)      0
dtype: int64

In [75]:
# weather.to_pickle('날씨(기상자료개방포털).pkl')