In [1]:
import pandas as pd

In [2]:
df0 = pd.read_csv('서울교통공사_1_8호선일별역별시간대별승하차인원_202001_202005.csv', encoding='cp949')
df1 = pd.read_excel('서울교통공사 2019년 일별 역별 시간대별 승하차인원(1_8호선).xlsx')

In [3]:
def make_day(df):
    if 'Unnamed: 0' in df.columns:
        df.columns = df.loc[0]
        df.drop(0, axis=0, inplace=True)
    else:
        pass
    
    df['날짜'] = pd.to_datetime(df['날짜'])
    df['요일'] = df['날짜'].dt.day_name()
    
    days = list(df['요일'])
    kor_day = []
    for day in days:
        if day == 'Friday':
            kor_day.append('금요일')
        elif day == 'Monday':
            kor_day.append('월요일')
        elif day == 'Saturday':
            kor_day.append('토요일')
        elif day == 'Sunday':
            kor_day.append('일요일')
        elif day == 'Thursday':
            kor_day.append('목요일')
        elif day == 'Tuesday':
                kor_day.append('화요일')
        elif day == 'Wednesday':
            kor_day.append('수요일')

    df['요일'] = kor_day
    
    return df

In [4]:
df0 =make_day(df0)
df1 =make_day(df1)

In [5]:
subway_all = pd.concat([df0, df1], axis=0)
subway_all.set_index('날짜', inplace=True)
subway_all.sort_index(inplace=True)
subway_all

,호선,역번호,역명,구분,06시 이전,06 ~ 07,07 ~ 08,08 ~ 09,09 ~ 10,10 ~ 11,...,17 ~ 18,18 ~ 19,19 ~ 20,20 ~ 21,21 ~ 22,22 ~ 23,23 ~ 24,24시 이후,합 계,요일
날짜,,,,,,,,,,,,,,,,,,,,,
2019-01-01,1호선,150,서울역,승차,348,321,348,741,940,1401,...,3447,3277,2898,2590,3004,2234,970,38,39559,화요일
2019-01-01,6호선,2630,녹사평(용산구청),승차,171,117,58,81,104,145,...,256,272,212,238,239,188,72,0,3506,화요일
2019-01-01,6호선,2629,삼각지,하차,46,89,64,80,105,138,...,154,128,152,157,116,152,80,14,2411,화요일
2019-01-01,6호선,2629,삼각지,승차,48,68,51,80,110,98,...,376,269,150,125,100,74,50,0,2981,화요일
2019-01-01,6호선,2628,효창공원앞,하차,24,76,64,103,129,110,...,214,213,179,149,163,145,80,12,2533,화요일
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-05-31,3호선,342,오금,승차,68,87,90,180,204,178,...,171,108,109,71,62,40,8,0,2512,일요일
2020-05-31,3호선,342,오금,하차,1,37,57,99,140,175,...,194,159,178,189,174,129,123,17,2462,일요일
2020-05-31,4호선,409,당고개,승차,117,151,269,458,598,532,...,513,534,318,273,230,126,38,3,7331,일요일
2020-05-31,3호선,340,가락시장,승차,39,66,92,161,187,217,...,228,227,180,171,166,116,41,0,3430,일요일
2020-05-31,8호선,2827,모란,하차,19,55,56,69,85,101,...,145,129,119,113,96,99,66,12,1951,일요일

# 특정 지하철역, 특정 기간, 특정 시간대 하차인원

## 명동으로 테스트

In [6]:
day = subway_all.loc['2020-05-31']['요일'][0]

In [7]:
df_of_the_day = subway_all[subway_all['요일'] == day]
df_of_the_day

,호선,역번호,역명,구분,06시 이전,06 ~ 07,07 ~ 08,08 ~ 09,09 ~ 10,10 ~ 11,...,17 ~ 18,18 ~ 19,19 ~ 20,20 ~ 21,21 ~ 22,22 ~ 23,23 ~ 24,24시 이후,합 계,요일
날짜,,,,,,,,,,,,,,,,,,,,,
2019-01-06,6호선,2624,상수,승차,164,159,100,153,189,211,...,510,568,572,615,716,760,427,0,7384,일요일
2019-01-06,6호선,2624,상수,하차,22,61,80,95,235,410,...,804,792,601,347,316,318,218,1,8339,일요일
2019-01-06,6호선,2625,광흥창(서강),승차,46,73,99,190,320,321,...,389,396,217,177,151,109,46,0,5127,일요일
2019-01-06,6호선,2625,광흥창(서강),하차,25,100,116,259,277,501,...,330,335,247,231,260,225,136,6,5140,일요일
2019-01-06,6호선,2626,대흥(서강대앞),승차,55,74,100,174,310,262,...,314,297,208,158,166,166,90,1,4217,일요일
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-05-31,3호선,342,오금,승차,68,87,90,180,204,178,...,171,108,109,71,62,40,8,0,2512,일요일
2020-05-31,3호선,342,오금,하차,1,37,57,99,140,175,...,194,159,178,189,174,129,123,17,2462,일요일
2020-05-31,4호선,409,당고개,승차,117,151,269,458,598,532,...,513,534,318,273,230,126,38,3,7331,일요일
2020-05-31,3호선,340,가락시장,승차,39,66,92,161,187,217,...,228,227,180,171,166,116,41,0,3430,일요일
2020-05-31,8호선,2827,모란,하차,19,55,56,69,85,101,...,145,129,119,113,96,99,66,12,1951,일요일

In [8]:
df_of_the_day[df_of_the_day['역명'] == '명동'].loc['2020-05-31']

,호선,역번호,역명,구분,06시 이전,06 ~ 07,07 ~ 08,08 ~ 09,09 ~ 10,10 ~ 11,...,17 ~ 18,18 ~ 19,19 ~ 20,20 ~ 21,21 ~ 22,22 ~ 23,23 ~ 24,24시 이후,합 계,요일
날짜,,,,,,,,,,,,,,,,,,,,,
2020-05-31,4호선,424,명동,하차,31,173,191,329,599,612,...,602,386,242,140,120,62,54,1,8820,일요일
2020-05-31,4호선,424,명동,승차,22,52,51,115,114,142,...,874,793,704,767,658,361,78,2,8218,일요일

In [9]:
test = df_of_the_day[df_of_the_day['역명'] == '명동']

In [10]:
test = test[test['구분'] == '하차']
test

,호선,역번호,역명,구분,06시 이전,06 ~ 07,07 ~ 08,08 ~ 09,09 ~ 10,10 ~ 11,...,17 ~ 18,18 ~ 19,19 ~ 20,20 ~ 21,21 ~ 22,22 ~ 23,23 ~ 24,24시 이후,합 계,요일
날짜,,,,,,,,,,,,,,,,,,,,,
2019-01-06,4호선,424,명동,하차,31,377,588,944,1473,1952,...,2454,1986,1537,1134,770,494,391,22,30600,일요일
2019-01-13,4호선,424,명동,하차,38,345,620,883,1582,2014,...,2682,2346,1716,1324,844,554,416,56,32502,일요일
2019-01-20,4호선,424,명동,하차,51,353,628,949,1598,1999,...,2645,2003,1598,1217,768,470,374,18,31999,일요일
2019-01-27,4호선,424,명동,하차,26,395,676,961,1668,2213,...,2832,2203,1683,1212,892,828,438,40,34484,일요일
2019-02-03,4호선,424,명동,하차,34,397,687,768,1341,1545,...,2292,1851,1522,1235,806,535,269,35,26889,일요일
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-05-03,4호선,424,명동,하차,22,196,182,340,485,659,...,668,488,400,230,122,63,52,12,9670,일요일
2020-05-10,4호선,424,명동,하차,29,198,199,340,480,708,...,561,406,293,172,111,46,45,1,8845,일요일
2020-05-17,4호선,424,명동,하차,34,169,213,317,543,700,...,566,412,272,183,119,72,38,3,8444,일요일
2020-05-24,4호선,424,명동,하차,26,159,156,298,504,654,...,585,466,288,197,122,57,37,6,8405,일요일
2020-05-31,4호선,424,명동,하차,31,173,191,329,599,612,...,602,386,242,140,120,62,54,1,8820,일요일

In [11]:
test.reset_index(inplace=True)

In [12]:
val = test[test['날짜'] == '2020-05-31'].index[0]
val

73

In [13]:
test.loc[val-6:val-1]['06 ~ 07']

67    148
68    170
69    196
70    198
71    169
72    159
Name: 06 ~ 07, dtype: object

In [14]:
test.loc[val-6:val-1]['06 ~ 07'].mean()

173.33333333333334

## 탐색을 용이하게 하기 위해 시간 칼럼 수정

In [15]:
time_col = list(subway_all.columns[4:-2])

In [16]:
time_col

['06시 이전',
 '06 ~ 07',
 '07 ~ 08',
 '08 ~ 09',
 '09 ~ 10',
 '10 ~ 11',
 '11 ~ 12',
 '12 ~ 13',
 '13 ~ 14',
 '14 ~ 15',
 '15 ~ 16',
 '16 ~ 17',
 '17 ~ 18',
 '18 ~ 19',
 '19 ~ 20',
 '20 ~ 21',
 '21 ~ 22',
 '22 ~ 23',
 '23 ~ 24',
 '24시 이후']

In [17]:
import re

In [18]:
temp = re.sub(' ~ ','-', time_col[1])

In [19]:
'0' in temp[0]

True

In [20]:
re.sub('0', '', temp)

'6-7'

In [21]:
new_time = []
for timeline in time_col:
    if '0' in timeline[0]:
        timeline = re.sub('0', '', timeline)
    else:
        pass
    timeline = re.sub(' ~ ','-', timeline)
    new_time.append(timeline)

In [22]:
new_time[0], new_time[4], new_time[-1] = '5-6', '9-10', '24-01'

In [23]:
new_time

['5-6',
 '6-7',
 '7-8',
 '8-9',
 '9-10',
 '10-11',
 '11-12',
 '12-13',
 '13-14',
 '14-15',
 '15-16',
 '16-17',
 '17-18',
 '18-19',
 '19-20',
 '20-21',
 '21-22',
 '22-23',
 '23-24',
 '24-01']

In [24]:
col_all = list(subway_all.columns)

In [25]:
col_all[4:-2] = new_time

In [26]:
subway_all.columns = col_all

In [27]:
subway_all

,호선,역번호,역명,구분,5-6,6-7,7-8,8-9,9-10,10-11,...,17-18,18-19,19-20,20-21,21-22,22-23,23-24,24-01,합 계,요일
날짜,,,,,,,,,,,,,,,,,,,,,
2019-01-01,1호선,150,서울역,승차,348,321,348,741,940,1401,...,3447,3277,2898,2590,3004,2234,970,38,39559,화요일
2019-01-01,6호선,2630,녹사평(용산구청),승차,171,117,58,81,104,145,...,256,272,212,238,239,188,72,0,3506,화요일
2019-01-01,6호선,2629,삼각지,하차,46,89,64,80,105,138,...,154,128,152,157,116,152,80,14,2411,화요일
2019-01-01,6호선,2629,삼각지,승차,48,68,51,80,110,98,...,376,269,150,125,100,74,50,0,2981,화요일
2019-01-01,6호선,2628,효창공원앞,하차,24,76,64,103,129,110,...,214,213,179,149,163,145,80,12,2533,화요일
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-05-31,3호선,342,오금,승차,68,87,90,180,204,178,...,171,108,109,71,62,40,8,0,2512,일요일
2020-05-31,3호선,342,오금,하차,1,37,57,99,140,175,...,194,159,178,189,174,129,123,17,2462,일요일
2020-05-31,4호선,409,당고개,승차,117,151,269,458,598,532,...,513,534,318,273,230,126,38,3,7331,일요일
2020-05-31,3호선,340,가락시장,승차,39,66,92,161,187,217,...,228,227,180,171,166,116,41,0,3430,일요일
2020-05-31,8호선,2827,모란,하차,19,55,56,69,85,101,...,145,129,119,113,96,99,66,12,1951,일요일

# 함수화

In [28]:
def find_pop(date, time, station, num):
    #지정한 날짜의 요일 확인
    day = subway_all.loc[date]['요일'][0]
    #해당 요일로만 구성된 데이터프레임 생성
    df_of_the_day = subway_all[subway_all['요일'] == day]
    
    #지정한 지하철역의 데이터프레임 생성
    temp = df_of_the_day[df_of_the_day['역명'] == station]
    #승하차 구분
    temp = temp[temp['구분'] == '하차']
    #인덱스를 reset시켜 인덱스에서의 1은 일주일을 뜻하게 함
    temp.reset_index(inplace=True)
    
    #해당 날짜의 인덱스를 확인
    val = temp[temp['날짜'] == date].index[0]
    #그로부터 지난 n주일까지의 특정 시간대, 특정 지하철역의 하차인원 평균 
    pop_mean = temp.loc[val-num-1:val-1][time].mean()
    
    return pop_mean

In [29]:
find_pop('2020-05-31', '6-7', '명동', 5)

173.33333333333334

# 서울역처럼, 환승이 있는 곳에 대해서 따로 해야될 필요성이 있다.

In [30]:
subway_all

,호선,역번호,역명,구분,5-6,6-7,7-8,8-9,9-10,10-11,...,17-18,18-19,19-20,20-21,21-22,22-23,23-24,24-01,합 계,요일
날짜,,,,,,,,,,,,,,,,,,,,,
2019-01-01,1호선,150,서울역,승차,348,321,348,741,940,1401,...,3447,3277,2898,2590,3004,2234,970,38,39559,화요일
2019-01-01,6호선,2630,녹사평(용산구청),승차,171,117,58,81,104,145,...,256,272,212,238,239,188,72,0,3506,화요일
2019-01-01,6호선,2629,삼각지,하차,46,89,64,80,105,138,...,154,128,152,157,116,152,80,14,2411,화요일
2019-01-01,6호선,2629,삼각지,승차,48,68,51,80,110,98,...,376,269,150,125,100,74,50,0,2981,화요일
2019-01-01,6호선,2628,효창공원앞,하차,24,76,64,103,129,110,...,214,213,179,149,163,145,80,12,2533,화요일
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-05-31,3호선,342,오금,승차,68,87,90,180,204,178,...,171,108,109,71,62,40,8,0,2512,일요일
2020-05-31,3호선,342,오금,하차,1,37,57,99,140,175,...,194,159,178,189,174,129,123,17,2462,일요일
2020-05-31,4호선,409,당고개,승차,117,151,269,458,598,532,...,513,534,318,273,230,126,38,3,7331,일요일
2020-05-31,3호선,340,가락시장,승차,39,66,92,161,187,217,...,228,227,180,171,166,116,41,0,3430,일요일
2020-05-31,8호선,2827,모란,하차,19,55,56,69,85,101,...,145,129,119,113,96,99,66,12,1951,일요일

In [31]:
day = subway_all.loc['2020-05-31']['요일'][0]
df_of_the_day = subway_all[subway_all['요일'] == day]
temp = df_of_the_day[df_of_the_day['역명'] == '서울역']
temp = temp[temp['구분'] == '하차']
temp = temp.groupby('날짜').sum()
temp.reset_index(inplace=True)

val = temp[temp['날짜'] == '2020-05-31'].index[0]
pop_mean = temp.loc[val-6:val-1]['6-7'].mean()

In [32]:
pop_mean

610.6666666666666

In [33]:
def find_pop_modified(date, time, station, num):
    #지정한 날짜의 요일 확인
    day = subway_all.loc[date]['요일'][0]
    #해당 요일로만 구성된 데이터프레임 생성
    df_of_the_day = subway_all[subway_all['요일'] == day]
    
    #지정한 지하철역의 데이터프레임 생성
    temp = df_of_the_day[df_of_the_day['역명'] == station]
    #승하차 구분
    temp = temp[temp['구분'] == '하차']
    #호선이 많은 노선의 경우 이를 날짜를 기준으로 합쳐주어야 할 필요성이 있음
    temp = temp.groupby('날짜').sum()
    
    #인덱스를 reset시켜 인덱스에서의 1은 일주일을 뜻하게 함
    temp.reset_index(inplace=True)
    
    #해당 날짜의 인덱스를 확인
    val = temp[temp['날짜'] == date].index[0]
    #그로부터 지난 n주일까지의 특정 시간대, 특정 지하철역의 하차인원 평균 
    pop_mean = temp.loc[val-num-1:val-1][time].mean()
    
    return pop_mean

### 단일역을 기준으로 했을 때, 바꾼 함수와 기존 함수의 비교

In [34]:
find_pop_modified('2020-05-31', '6-7', '명동', 6)

171.42857142857142

In [35]:
find_pop('2020-05-31', '6-7', '명동', 6)

171.42857142857142

# 공휴일 처리 문제
- 공휴일, 주말을 라벨링을 해야 한다.
- 주중이면 0, 주말 & 공휴일이면 1로
- 평일일 때 공휴일이면 이를 어떻게 처리해야할지
- 가장 가까운 이전 주말을 기준으로?

In [36]:
subway_all['공휴일'] = 0

In [37]:
import copy
subway_backup = copy.deepcopy(subway_all)

In [38]:
subway_all

,호선,역번호,역명,구분,5-6,6-7,7-8,8-9,9-10,10-11,...,18-19,19-20,20-21,21-22,22-23,23-24,24-01,합 계,요일,공휴일
날짜,,,,,,,,,,,,,,,,,,,,,
2019-01-01,1호선,150,서울역,승차,348,321,348,741,940,1401,...,3277,2898,2590,3004,2234,970,38,39559,화요일,0
2019-01-01,6호선,2630,녹사평(용산구청),승차,171,117,58,81,104,145,...,272,212,238,239,188,72,0,3506,화요일,0
2019-01-01,6호선,2629,삼각지,하차,46,89,64,80,105,138,...,128,152,157,116,152,80,14,2411,화요일,0
2019-01-01,6호선,2629,삼각지,승차,48,68,51,80,110,98,...,269,150,125,100,74,50,0,2981,화요일,0
2019-01-01,6호선,2628,효창공원앞,하차,24,76,64,103,129,110,...,213,179,149,163,145,80,12,2533,화요일,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-05-31,3호선,342,오금,승차,68,87,90,180,204,178,...,108,109,71,62,40,8,0,2512,일요일,0
2020-05-31,3호선,342,오금,하차,1,37,57,99,140,175,...,159,178,189,174,129,123,17,2462,일요일,0
2020-05-31,4호선,409,당고개,승차,117,151,269,458,598,532,...,534,318,273,230,126,38,3,7331,일요일,0
2020-05-31,3호선,340,가락시장,승차,39,66,92,161,187,217,...,227,180,171,166,116,41,0,3430,일요일,0
2020-05-31,8호선,2827,모란,하차,19,55,56,69,85,101,...,129,119,113,96,99,66,12,1951,일요일,0

In [39]:
temp_holiday = subway_all[['요일', '공휴일']]

In [40]:
temp_holiday.reset_index(inplace=True)

In [41]:
temp_holiday

               날짜   요일  공휴일
0      2019-01-01  화요일    0
1      2019-01-01  화요일    0
2      2019-01-01  화요일    0
3      2019-01-01  화요일    0
4      2019-01-01  화요일    0
...           ...  ...  ...
284555 2020-05-31  일요일    0
284556 2020-05-31  일요일    0
284557 2020-05-31  일요일    0
284558 2020-05-31  일요일    0
284559 2020-05-31  일요일    0

[284560 rows x 3 columns]

## 토요일과 일요일 공휴일 처리

In [42]:
sun_index = temp_holiday[temp_holiday['요일'] == '일요일']['공휴일'].index

In [43]:
temp_holiday['공휴일'][sun_index] = 1
# temp.loc[indexes]['공휴일'] = '1' <-- 이 경우에는 먹히지가 않았다

C:\Users\sb\anaconda3\envs\nlp\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\sb\anaconda3\envs\nlp\lib\site-packages\pandas\core\series.py:1092: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._set_labels(key, value)
C:\Users\sb\anaconda3\envs\nlp\lib\site-packages\IPython\core\interactiveshell.py:3343: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)

In [44]:
sat_index = temp_holiday[temp_holiday['요일'] == '토요일'].index

In [45]:
temp_holiday['공휴일'][sat_index] = 1

C:\Users\sb\anaconda3\envs\nlp\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [46]:
temp_holiday[temp_holiday['요일'] == '토요일']

               날짜   요일  공휴일
2200   2019-01-05  토요일    1
2201   2019-01-05  토요일    1
2202   2019-01-05  토요일    1
2203   2019-01-05  토요일    1
2204   2019-01-05  토요일    1
...           ...  ...  ...
284005 2020-05-30  토요일    1
284006 2020-05-30  토요일    1
284007 2020-05-30  토요일    1
284008 2020-05-30  토요일    1
284009 2020-05-30  토요일    1

[40726 rows x 3 columns]

In [47]:
subway_all.reset_index(inplace=True)
subway_all['공휴일'] = temp_holiday['공휴일']

In [48]:
subway_all

,날짜,호선,역번호,역명,구분,5-6,6-7,7-8,8-9,9-10,...,18-19,19-20,20-21,21-22,22-23,23-24,24-01,합 계,요일,공휴일
0,2019-01-01,1호선,150,서울역,승차,348,321,348,741,940,...,3277,2898,2590,3004,2234,970,38,39559,화요일,0
1,2019-01-01,6호선,2630,녹사평(용산구청),승차,171,117,58,81,104,...,272,212,238,239,188,72,0,3506,화요일,0
2,2019-01-01,6호선,2629,삼각지,하차,46,89,64,80,105,...,128,152,157,116,152,80,14,2411,화요일,0
3,2019-01-01,6호선,2629,삼각지,승차,48,68,51,80,110,...,269,150,125,100,74,50,0,2981,화요일,0
4,2019-01-01,6호선,2628,효창공원앞,하차,24,76,64,103,129,...,213,179,149,163,145,80,12,2533,화요일,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284555,2020-05-31,3호선,342,오금,승차,68,87,90,180,204,...,108,109,71,62,40,8,0,2512,일요일,1
284556,2020-05-31,3호선,342,오금,하차,1,37,57,99,140,...,159,178,189,174,129,123,17,2462,일요일,1
284557,2020-05-31,4호선,409,당고개,승차,117,151,269,458,598,...,534,318,273,230,126,38,3,7331,일요일,1
284558,2020-05-31,3호선,340,가락시장,승차,39,66,92,161,187,...,227,180,171,166,116,41,0,3430,일요일,1
284559,2020-05-31,8호선,2827,모란,하차,19,55,56,69,85,...,129,119,113,96,99,66,12,1951,일요일,1

## 설날로 테스트

In [49]:
subway_all.set_index('날짜', inplace=True)

In [50]:
subway_all.loc['2020-01-24':'2020-01-27']['공휴일'] = 1

C:\Users\sb\anaconda3\envs\nlp\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

### 주말은 공휴일에 딱히 상관이 없다. 
- 중요한건 평일인데 공휴일인애들인거잖아?
- 단지 공휴일인것만을 기준으로 둔다면, 과거 데이터를 기준으로 봤을 때, 주말인데 그 이전 주말 사이에 공휴일이 들어갔다면 이를 어떻게 볼 것인가?
- 설날이나 추석의 경우에는 일반 주말과는 다를텐데 이를 또 어떻게 볼 것인가?

### 우선은 연속적인 공휴일이 아니라 하루치의 공휴일로

In [52]:
subway_all.loc['2020-04-30']['공휴일'] = 1

C:\Users\sb\anaconda3\envs\nlp\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [53]:
subway_all.loc['2020-04-30']

,호선,역번호,역명,구분,5-6,6-7,7-8,8-9,9-10,10-11,...,18-19,19-20,20-21,21-22,22-23,23-24,24-01,합 계,요일,공휴일
날짜,,,,,,,,,,,,,,,,,,,,,
2020-04-30,6호선,2623,합정,하차,31,151,169,218,319,396,...,691,646,335,321,316,249,0,8805,목요일,1
2020-04-30,6호선,2624,상수,승차,88,113,97,128,178,162,...,438,431,499,576,628,353,1,5916,목요일,1
2020-04-30,6호선,2624,상수,하차,21,66,60,81,222,323,...,646,533,345,216,186,136,0,6989,목요일,1
2020-04-30,6호선,2625,광흥창(서강),승차,79,109,145,171,251,250,...,282,165,174,164,120,53,0,4004,목요일,1
2020-04-30,6호선,2625,광흥창(서강),하차,31,77,100,172,170,151,...,269,228,194,189,185,139,0,3559,목요일,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-04-30,3호선,341,경찰병원,하차,4,78,74,104,114,107,...,263,198,193,165,166,145,8,2789,목요일,1
2020-04-30,3호선,342,오금,승차,83,86,182,230,264,241,...,127,87,82,72,37,10,0,2764,목요일,1
2020-04-30,3호선,342,오금,하차,1,43,65,82,107,87,...,206,185,175,178,191,162,16,2471,목요일,1
2020-04-30,4호선,409,당고개,승차,208,264,406,638,636,664,...,517,373,249,232,169,49,0,9448,목요일,1
2020-04-30,3호선,340,가락시장,승차,78,134,207,242,286,345,...,278,205,183,189,173,52,1,4801,목요일,1

In [57]:
subway_all.to_csv('공휴일데이터용.csv')

In [58]:
subway_all

,호선,역번호,역명,구분,5-6,6-7,7-8,8-9,9-10,10-11,...,18-19,19-20,20-21,21-22,22-23,23-24,24-01,합 계,요일,공휴일
날짜,,,,,,,,,,,,,,,,,,,,,
2019-01-01,1호선,150,서울역,승차,348,321,348,741,940,1401,...,3277,2898,2590,3004,2234,970,38,39559,화요일,0
2019-01-01,6호선,2630,녹사평(용산구청),승차,171,117,58,81,104,145,...,272,212,238,239,188,72,0,3506,화요일,0
2019-01-01,6호선,2629,삼각지,하차,46,89,64,80,105,138,...,128,152,157,116,152,80,14,2411,화요일,0
2019-01-01,6호선,2629,삼각지,승차,48,68,51,80,110,98,...,269,150,125,100,74,50,0,2981,화요일,0
2019-01-01,6호선,2628,효창공원앞,하차,24,76,64,103,129,110,...,213,179,149,163,145,80,12,2533,화요일,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-05-31,3호선,342,오금,승차,68,87,90,180,204,178,...,108,109,71,62,40,8,0,2512,일요일,1
2020-05-31,3호선,342,오금,하차,1,37,57,99,140,175,...,159,178,189,174,129,123,17,2462,일요일,1
2020-05-31,4호선,409,당고개,승차,117,151,269,458,598,532,...,534,318,273,230,126,38,3,7331,일요일,1
2020-05-31,3호선,340,가락시장,승차,39,66,92,161,187,217,...,227,180,171,166,116,41,0,3430,일요일,1
2020-05-31,8호선,2827,모란,하차,19,55,56,69,85,101,...,129,119,113,96,99,66,12,1951,일요일,1

In [ ]:
subway = pd.read_csv('공휴일데이터용.csv')
subway.set_index('날짜', inplace=True)

In [62]:
df_holiday = subway[subway['공휴일'] == 1]
df_temp = df_holiday[df_holiday['역명'] == '서울역']
df_temp = df_temp[df_temp['구분'] == '하차']
df_temp = df_temp.groupby('날짜').sum()
df_temp.reset_index(inplace=True)
val = df_temp[df_temp['날짜'] == '2020-04-30'].index[0]
df_temp.loc[val-num-1:val-1]['6-7'].mean()

735.6666666666666

In [78]:
#평일인데다, 공휴일인지를 체크
subway_all.loc[date]['공휴일'][0] == 1 and subway_all.loc[date]['요일'][0] != '토요일' and subway_all.loc[date]['요일'][0] != '일요일'

True

In [81]:
def find_pop_fin(date, time, station, num):
    #공휴일 확인, 공휴일의 label 은 1, 평일은 0, 주말은 제외하고 평일인 공휴일 확인
    if subway_all.loc[date]['공휴일'][0] == 1 and subway_all.loc[date]['요일'][0] != '토요일' and subway_all.loc[date]['요일'][0] != '일요일':
        #공휴일인 데이터프레임 생성
        df_holiday = subway[subway['공휴일'] == 1]
        df_temp = df_holiday[df_holiday['역명'] == station]
        df_temp = df_temp[df_temp['구분'] == '하차']
        
        df_temp = df_temp.groupby('날짜').sum()
        df_temp.reset_index(inplace=True)
        
        val = df_temp[df_temp['날짜'] == date].index[0]
        holiday_pop_mean = df_temp.loc[val-num-1:val-1][time].mean()
        return holiday_pop_mean
    else:
        pass
    
    #지정한 날짜의 요일 확인
    day = subway_all.loc[date]['요일'][0]
    #해당 요일로만 구성된 데이터프레임 생성
    df_of_the_day = subway_all[subway_all['요일'] == day]
    
    #지정한 지하철역의 데이터프레임 생성
    temp = df_of_the_day[df_of_the_day['역명'] == station]
    #승하차 구분
    temp = temp[temp['구분'] == '하차']
    #호선이 많은 노선의 경우 이를 날짜를 기준으로 합쳐주어야 할 필요성이 있음
    temp = temp.groupby('날짜').sum()
    
    #인덱스를 reset시켜 인덱스에서의 1은 일주일을 뜻하게 함
    temp.reset_index(inplace=True)
    
    #해당 날짜의 인덱스를 확인
    val = temp[temp['날짜'] == date].index[0]
    #그로부터 지난 n주일까지의 특정 시간대, 특정 지하철역의 하차인원 평균 
    pop_mean = temp.loc[val-num-1:val-1][time].mean()
    
    return pop_mean

In [84]:
find_pop_fin('2020-04-30', '6-7', '서울역', 5)

735.6666666666666

# 공공데이터 공휴일 정보
- 특일정보 (https://www.data.go.kr/data/15012690/openapi.do)

In [ ]:
import requests

def get_request_query(url, operation, params, serviceKey):
    import urllib.parse as urlparse
    params = urlparse.urlencode(params)
    request_query = url + '/' + operation + '?' + params + '&' + 'serviceKey' + '=' + serviceKey
    return request_query

In [90]:
# 요청 URL과 오퍼레이션
URL = 'http://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService'
OPERATION = 'getHoliDeInfo' # 국경일 + 공휴일 정보 조회 오퍼레이션

# 파라미터
SERVICEKEY = '' #서비스 키값 입력
solYear  = '2020'  # 연도
# solMonth = '01'   # 월
PARAMS = {'solYear':solYear}


request_query = get_request_query(URL, OPERATION, PARAMS, SERVICEKEY)
# print('request_query:', request_query)
response = requests.get(url=request_query)
# print('status_code:' + str(response.status_code))

# if True == response.ok:
#     print(response.text)

In [92]:
from bs4 import BeautifulSoup

In [96]:
soup = BeautifulSoup(response.content, 'lxml')

In [98]:
data = soup.find_all('item')

In [130]:
holiday_list = []
for item in data:
    datename = item.find('datename')
    locdate = item.find('locdate')
    holiday_list.append([datename.get_text(), locdate.get_text()])

In [132]:
holiday_list

[['1월1일', '20200101'],
 ['설날', '20200124'],
 ['설날', '20200125'],
 ['설날', '20200126'],
 ['설날', '20200127'],
 ['삼일절', '20200301'],
 ['제21대 국회의원선거', '20200415'],
 ['부처님오신날', '20200430'],
 ['어린이날', '20200505'],
 ['현충일', '20200606']]

In [152]:
holiday = pd.DataFrame(holiday_list, columns = ['공휴일', '날짜'])

In [158]:
holiday['날짜']

0    20200101
1    20200124
2    20200125
3    20200126
4    20200127
5    20200301
6    20200415
7    20200430
8    20200505
9    20200606
Name: 날짜, dtype: object

In [121]:
holiday

Empty DataFrame
Columns: [날짜, 공휴일]
Index: []

In [161]:
holiday_date = list(holiday['날짜'])

In [163]:
import re

In [166]:
test =holiday_date[0]

In [170]:
test[:4] + '-' + test[4:6] + '-' +test[6:]

'2020-01-01'

In [171]:
date_modi = []
for holi in holiday_date:
    date_modi.append(holi[:4] + '-' + holi[4:6] + '-' + holi[6:])

In [172]:
date_modi

['2020-01-01',
 '2020-01-24',
 '2020-01-25',
 '2020-01-26',
 '2020-01-27',
 '2020-03-01',
 '2020-04-15',
 '2020-04-30',
 '2020-05-05',
 '2020-06-06']

In [136]:
subway

,호선,역번호,역명,구분,5-6,6-7,7-8,8-9,9-10,10-11,...,18-19,19-20,20-21,21-22,22-23,23-24,24-01,합 계,요일,공휴일
날짜,,,,,,,,,,,,,,,,,,,,,
2019-01-01,1호선,150,서울역,승차,348,321,348,741,940,1401,...,3277,2898,2590,3004,2234,970,38,39559,화요일,0
2019-01-01,6호선,2630,녹사평(용산구청),승차,171,117,58,81,104,145,...,272,212,238,239,188,72,0,3506,화요일,0
2019-01-01,6호선,2629,삼각지,하차,46,89,64,80,105,138,...,128,152,157,116,152,80,14,2411,화요일,0
2019-01-01,6호선,2629,삼각지,승차,48,68,51,80,110,98,...,269,150,125,100,74,50,0,2981,화요일,0
2019-01-01,6호선,2628,효창공원앞,하차,24,76,64,103,129,110,...,213,179,149,163,145,80,12,2533,화요일,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-05-31,3호선,342,오금,승차,68,87,90,180,204,178,...,108,109,71,62,40,8,0,2512,일요일,1
2020-05-31,3호선,342,오금,하차,1,37,57,99,140,175,...,159,178,189,174,129,123,17,2462,일요일,1
2020-05-31,4호선,409,당고개,승차,117,151,269,458,598,532,...,534,318,273,230,126,38,3,7331,일요일,1
2020-05-31,3호선,340,가락시장,승차,39,66,92,161,187,217,...,227,180,171,166,116,41,0,3430,일요일,1
2020-05-31,8호선,2827,모란,하차,19,55,56,69,85,101,...,129,119,113,96,99,66,12,1951,일요일,1

In [179]:
holiday['날짜'] = date_modi

In [180]:
holiday

           공휴일          날짜
0         1월1일  2020-01-01
1           설날  2020-01-24
2           설날  2020-01-25
3           설날  2020-01-26
4           설날  2020-01-27
5          삼일절  2020-03-01
6  제21대 국회의원선거  2020-04-15
7       부처님오신날  2020-04-30
8         어린이날  2020-05-05
9          현충일  2020-06-06

In [139]:
subway_all.loc['2020-04-30']['공휴일'] = 1

           공휴일         날짜
0         1월1일 2020-01-01
1           설날 2020-01-24
2           설날 2020-01-25
3           설날 2020-01-26
4           설날 2020-01-27
5          삼일절 2020-03-01
6  제21대 국회의원선거 2020-04-15
7       부처님오신날 2020-04-30
8         어린이날 2020-05-05
9          현충일 2020-06-06

In [181]:
subway.loc[]

,호선,역번호,역명,구분,5-6,6-7,7-8,8-9,9-10,10-11,...,18-19,19-20,20-21,21-22,22-23,23-24,24-01,합 계,요일,공휴일
날짜,,,,,,,,,,,,,,,,,,,,,
2019-01-01,1호선,150,서울역,승차,348,321,348,741,940,1401,...,3277,2898,2590,3004,2234,970,38,39559,화요일,0
2019-01-01,6호선,2630,녹사평(용산구청),승차,171,117,58,81,104,145,...,272,212,238,239,188,72,0,3506,화요일,0
2019-01-01,6호선,2629,삼각지,하차,46,89,64,80,105,138,...,128,152,157,116,152,80,14,2411,화요일,0
2019-01-01,6호선,2629,삼각지,승차,48,68,51,80,110,98,...,269,150,125,100,74,50,0,2981,화요일,0
2019-01-01,6호선,2628,효창공원앞,하차,24,76,64,103,129,110,...,213,179,149,163,145,80,12,2533,화요일,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-05-31,3호선,342,오금,승차,68,87,90,180,204,178,...,108,109,71,62,40,8,0,2512,일요일,1
2020-05-31,3호선,342,오금,하차,1,37,57,99,140,175,...,159,178,189,174,129,123,17,2462,일요일,1
2020-05-31,4호선,409,당고개,승차,117,151,269,458,598,532,...,534,318,273,230,126,38,3,7331,일요일,1
2020-05-31,3호선,340,가락시장,승차,39,66,92,161,187,217,...,227,180,171,166,116,41,0,3430,일요일,1
2020-05-31,8호선,2827,모란,하차,19,55,56,69,85,101,...,129,119,113,96,99,66,12,1951,일요일,1

In [183]:
for date in holiday['날짜'][:-1]:
    subway.loc[date]['공휴일'] = 1

C:\Users\sb\anaconda3\envs\nlp\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [185]:
subway.loc['2020-01-24']

,호선,역번호,역명,구분,5-6,6-7,7-8,8-9,9-10,10-11,...,18-19,19-20,20-21,21-22,22-23,23-24,24-01,합 계,요일,공휴일
날짜,,,,,,,,,,,,,,,,,,,,,
2020-01-24,6호선,2625,광흥창(서강),승차,54,76,78,121,232,241,...,165,130,82,84,103,34,0,3154,금요일,1
2020-01-24,6호선,2625,광흥창(서강),하차,32,50,70,97,108,101,...,215,204,166,153,152,102,1,2738,금요일,1
2020-01-24,6호선,2626,대흥(서강대앞),승차,59,65,90,131,187,170,...,197,144,137,116,110,49,2,3181,금요일,1
2020-01-24,6호선,2626,대흥(서강대앞),하차,23,48,64,118,125,121,...,213,192,138,149,116,153,5,2842,금요일,1
2020-01-24,6호선,2627,공덕,승차,106,149,136,225,261,282,...,433,359,296,272,233,124,0,6173,금요일,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-01-24,3호선,342,오금,승차,58,81,153,198,208,224,...,108,74,79,55,29,12,0,2637,금요일,1
2020-01-24,3호선,342,오금,하차,3,43,35,49,60,82,...,149,135,123,106,126,107,15,1980,금요일,1
2020-01-24,4호선,409,당고개,승차,102,156,223,395,486,462,...,404,314,260,196,115,43,1,6827,금요일,1
2020-01-24,4호선,409,당고개,하차,3,143,122,185,275,307,...,540,523,399,412,372,334,58,6875,금요일,1
2020-01-24,3호선,340,가락시장,하차,15,111,97,149,223,274,...,310,180,158,139,142,103,26,4192,금요일,1